# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serchkamar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import detailkamar_rc
# from detailkamarbiasa import Ui_MainWindow as Ui_DetailKamarBiasa
from detailkamarvip import Ui_MainWindow as Ui_DetailKamarVip
from detailkamarvvip import Ui_MainWindow as Ui_DetailKamarVvip
from pembayarankosbiasa import Ui_MainWindow as  Ui_Pembayarankosbiasa
from pembayarankosvip import Ui_MainWindow as  Ui_Pembayarankosvip
from pembayarankosvvip import Ui_MainWindow as  Ui_Pembayarankosvvip
import user
from login import Ui_MainWindow as LoginUI
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
        def setupUi(self, MainWindow, role="tamu"):
                self.role = role
                self.MainWindow = MainWindow
   # simpan status: "penghuni" atau "tamu"


                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(723, 1012)
                font = QtGui.QFont()
                font.setFamily("Verdana")
                MainWindow.setFont(font)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(530, 560, 161, 191))
                self.label.setStyleSheet("border-image: url(:/vip/vip.jpeg);\n"
        "background-size: cover;")
                self.label.setText("")
                self.label.setObjectName("label")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.clicked.connect(self.cariKamar)

                self.pushButton.setGeometry(QtCore.QRect(480, 320, 111, 31))
                self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
        "    /* Background Gradient Default */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219), /* Biru Tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)); /* Abu-abu Kebiruan */\n"
        "        \n"
        "    color: rgba(255, 255, 255, 255); /* Teks Putih Solid (lebih jelas) */\n"
        "    border-radius: 8px; /* Menggunakan 8px agar konsisten dengan elemen lain */\n"
        "    border: none; /* Pastikan tidak ada border bawaan */\n"
        "    padding: 10px 25px; /* Padding untuk tombol agar terlihat tebal */\n"
        "    font-size: 14px; /* Ukuran font yang konsisten */\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton#pushButton:hover {\n"
        "    /* Gradient Hover: Warna sedikit lebih cerah/kontras */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(40, 67, 98, 219), /* Biru Tua Sedikit Cerah */\n"
        "        stop:1 rgba(105, 118, 132, 226)); /* Abu-abu Kebiruan Sedikit Cerah */\n"
        "}\n"
        "\n"
        "QPushButton#pushButton:pressed {\n"
        "    /* Efek Pressed (Tombol Tertekan) */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    /* Memberikan ilusi tombol bergerak ke dalam */\n"
        "    background-color: rgba(105, 118, 132, 255); /* Warna solid yang lebih gelap/tertarik */\n"
        "    border-style: inset; /* Opsi lain: inset border */\n"
        "}")
                self.pushButton.setObjectName("pushButton")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(210, 370, 481, 181))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(20)
                self.label_3.setFont(font)
                self.label_3.setStyleSheet("background-color: qlineargradient(\n"
        "        spread:pad, \n"
        "        x1:0, y1:0, \n"
        "        x2:0, y2:0.715909, \n"
        "        /* Mulai dengan Abu-abu Sangat Terang (hampir putih) */\n"
        "        stop:0 rgba(240, 240, 240, 200),  \n"
        "        /* Tengah: Abu-abu Terang */\n"
        "        stop:0.375 rgba(220, 220, 220, 200), \n"
        "        /* Akhir: Abu-abu Agak Sedang */\n"
        "        stop:0.835227 rgba(200, 200, 200, 200) \n"
        "    );\n"
        "    \n"
        "    border-radius: 20px;")
                self.label_3.setText("")
                self.label_3.setObjectName("label_3")
                self.label_13 = QtWidgets.QLabel(self.centralwidget)
                self.label_13.setGeometry(QtCore.QRect(510, 390, 171, 31))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(19)
                font.setBold(True)
                font.setWeight(75)
                self.label_13.setFont(font)
                self.label_13.setStyleSheet("color: rgba(140, 100, 70, 1);\n"
        "")
                self.label_13.setObjectName("label_13")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(40, 760, 151, 181))
                self.label_2.setStyleSheet("border-image: url(:/vvip/vvip.jpeg);\n"
        "background-size: cover;")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.label_biasa = QtWidgets.QLabel(self.centralwidget)
                self.label_biasa.setGeometry(QtCore.QRect(40, 370, 161, 181))
                self.label_biasa.setStyleSheet("border-image: url(:/biasa/biasa.jpeg);\n"
        "background-size: cover;")
                self.label_biasa.setText("")
                self.label_biasa.setObjectName("label_biasa")
                self.detailButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.detailButton_2.clicked.connect(self.bukaDetailBiasa)

                self.detailButton_2.setGeometry(QtCore.QRect(230, 500, 251, 41))
                self.detailButton_2.setStyleSheet("QPushButton#detailButton_2 {\n"
        "    background-color: transparent; /* Background clear */\n"
        "    color: rgba(255, 255, 255, 255); \n"
        "    border: 2px solid rgba(255, 255, 255, 180); /* Border putih transparan */\n"
        "    border-radius: 8px;\n"
        "    padding: 10px 25px;\n"
        "    font-size: 14px;\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "/* Hover: border lebih terang + sedikit glow */\n"
        "QPushButton#detailButton_2:hover {\n"
        "    background-color: rgba(255, 255, 255, 20); /* Transparan tipis */\n"
        "    border: 2px solid rgba(255, 255, 255, 220);\n"
        "}\n"
        "\n"
        "/* Pressed: background berubah jadi GRADIENT biru */\n"
        "QPushButton#detailButton_2:pressed {\n"
        "    background-color: qlineargradient(\n"
        "        spread:pad, \n"
        "        x1:0, y1:0.505682, \n"
        "        x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219),   /* Biru tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)   /* Biru abu */\n"
        "    );\n"
        "    border: 2px solid rgba(255, 255, 255, 255); /* Border tetap putih */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "}\n"
        "")
                self.detailButton_2.setObjectName("detailButton_2")
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(40, 80, 651, 221))
                self.label_7.setStyleSheet("border-image: url(:/header/gerbang.jpg);")
                self.label_7.setText("")
                self.label_7.setObjectName("label_7")
                self.label_11 = QtWidgets.QLabel(self.centralwidget)
                self.label_11.setGeometry(QtCore.QRect(230, 390, 261, 41))
                font = QtGui.QFont()
                font.setFamily("Verdana")
                font.setPointSize(23)
                font.setBold(True)
                font.setWeight(75)
                self.label_11.setFont(font)
                self.label_11.setStyleSheet("")
                self.label_11.setObjectName("label_11")
                self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_3.clicked.connect(self.ui_bukapembayaranbiasa)
                self.pushButton_3.setGeometry(QtCore.QRect(490, 500, 161, 41))
                self.pushButton_3.setStyleSheet("QPushButton#pushButton_3 {\n"
        "    /* Background Gradient Default */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219), /* Biru Tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)); /* Abu-abu Kebiruan */\n"
        "        \n"
        "    color: rgba(255, 255, 255, 255); /* Teks Putih Solid (lebih jelas) */\n"
        "    border-radius: 8px; /* Menggunakan 8px agar konsisten dengan elemen lain */\n"
        "    border: none; /* Pastikan tidak ada border bawaan */\n"
        "    padding: 10px 25px; /* Padding untuk tombol agar terlihat tebal */\n"
        "    font-size: 14px; /* Ukuran font yang konsisten */\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton#pushButton_3:hover {\n"
        "    /* Gradient Hover: Warna sedikit lebih cerah/kontras */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(40, 67, 98, 219), /* Biru Tua Sedikit Cerah */\n"
        "        stop:1 rgba(105, 118, 132, 226)); /* Abu-abu Kebiruan Sedikit Cerah */\n"
        "}\n"
        "\n"
        "QPushButton#pushButton_3:pressed {\n"
        "    /* Efek Pressed (Tombol Tertekan) */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    /* Memberikan ilusi tombol bergerak ke dalam */\n"
        "    background-color: rgba(105, 118, 132, 255); /* Warna solid yang lebih gelap/tertarik */\n"
        "    border-style: inset; /* Opsi lain: inset border */\n"

        "}")
                self.pushButton_3.setObjectName("pushButton_3")
                self.detailButton_8 = QtWidgets.QPushButton(self.centralwidget)
                self.detailButton_8.clicked.connect(self.kembali)

                self.detailButton_8.setGeometry(QtCore.QRect(10, 30, 141, 31))
                self.detailButton_8.setStyleSheet("QPushButton#detailButton_8 {\n"
        "    /* Background Gradient Default */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219), /* Biru Tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)); /* Abu-abu Kebiruan */\n"
        "        \n"
        "    color: rgba(255, 255, 255, 255); /* Teks Putih Solid (lebih jelas) */\n"
        "    border-radius: 8px; /* Menggunakan 8px agar konsisten dengan elemen lain */\n"
        "    border: none; /* Pastikan tidak ada border bawaan */\n"
        "    padding: 10px 25px; /* Padding untuk tombol agar terlihat tebal */\n"
        "    font-size: 14px; /* Ukuran font yang konsisten */\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton#detailButton_8:hover {\n"
        "    /* Gradient Hover: Warna sedikit lebih cerah/kontras */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(40, 67, 98, 219), /* Biru Tua Sedikit Cerah */\n"
        "        stop:1 rgba(105, 118, 132, 226)); /* Abu-abu Kebiruan Sedikit Cerah */\n"
        "}\n"
        "\n"
        "QPushButton#detailButton_8:pressed {\n"
        "    /* Efek Pressed (Tombol Tertekan) */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    /* Memberikan ilusi tombol bergerak ke dalam */\n"
        "    background-color: rgba(105, 118, 132, 255); /* Warna solid yang lebih gelap/tertarik */\n"
        "    border-style: inset; /* Opsi lain: inset border */\n"
        "}")
                self.detailButton_8.setObjectName("detailButton_8")
                self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit.setGeometry(QtCore.QRect(150, 320, 311, 31))
                self.lineEdit.setStyleSheet("background-color: qlineargradient(\n"
        "    spread:pad,\n"
        "    x1:0, y1:0, x2:0, y2:1,\n"
        "    stop:0 rgba(0, 0, 0, 9),\n"
        "    stop:0.375 rgba(0, 0, 0, 50),\n"
        "    stop:0.835227 rgba(0, 0, 0, 75)\n"
        ");\n"
        "border-radius: 20px;\n"
        "\n"
        "border-bottom: 2px solid white;\n"
        "")
                self.lineEdit.setObjectName("lineEdit")
                self.label_8 = QtWidgets.QLabel(self.centralwidget)
                self.label_8.setGeometry(QtCore.QRect(40, 80, 651, 221))
                font = QtGui.QFont()
                font.setFamily("Verdana")
                font.setPointSize(20)
                self.label_8.setFont(font)
                self.label_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
        "border-radius:20px;")
                self.label_8.setText("")
                self.label_8.setObjectName("label_8")
                self.label_9 = QtWidgets.QLabel(self.centralwidget)
                self.label_9.setGeometry(QtCore.QRect(210, 100, 311, 91))
                font = QtGui.QFont()
                font.setFamily("Century Schoolbook")
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.label_9.setFont(font)
                self.label_9.setStyleSheet("color:rgba(255,255,255,210);")
                self.label_9.setObjectName("label_9")
                self.label_10 = QtWidgets.QLabel(self.centralwidget)
                self.label_10.setGeometry(QtCore.QRect(210, 180, 221, 16))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setBold(True)
                font.setWeight(75)
                self.label_10.setFont(font)
                self.label_10.setStyleSheet("color:rgba(255,255,255,210);")
                self.label_10.setObjectName("label_10")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(40, 570, 481, 181))
                self.label_4.setStyleSheet("background-color: qlineargradient(\n"
        "        spread:pad, \n"
        "        x1:0, y1:0, \n"
        "        x2:0, y2:0.715909, \n"
        "        /* Mulai dengan Abu-abu Sangat Terang (hampir putih) */\n"
        "        stop:0 rgba(240, 240, 240, 200),  \n"
        "        /* Tengah: Abu-abu Terang */\n"
        "        stop:0.375 rgba(220, 220, 220, 200), \n"
        "        /* Akhir: Abu-abu Agak Sedang */\n"
        "        stop:0.835227 rgba(200, 200, 200, 200) \n"
        "    );\n"
        "    \n"
        "    border-radius: 20px;")
                self.label_4.setText("")
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(200, 760, 491, 191))
                self.label_5.setStyleSheet("background-color: qlineargradient(\n"
        "        spread:pad, \n"
        "        x1:0, y1:0, \n"
        "        x2:0, y2:0.715909, \n"
        "        /* Mulai dengan Abu-abu Sangat Terang (hampir putih) */\n"
        "        stop:0 rgba(240, 240, 240, 200),  \n"
        "        /* Tengah: Abu-abu Terang */\n"
        "        stop:0.375 rgba(220, 220, 220, 200), \n"
        "        /* Akhir: Abu-abu Agak Sedang */\n"
        "        stop:0.835227 rgba(200, 200, 200, 200) \n"
        "    );\n"
        "    \n"
        "    border-radius: 20px;")
                self.label_5.setText("")
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(210, 10, 321, 61))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.label_6.setFont(font)
                self.label_6.setStyleSheet("color: #333333; /* Abu-abu gelap yang elegan */\n"
        "    font-family: \"Segoe UI\", \"Arial\", sans-serif;\n"
        "    font-size: 30px;\n"
        "    font-weight: bold; /* Gunakan bold, bukan super bold */\n"
        "    padding-bottom: 10px")
                self.label_6.setObjectName("label_6")
                self.label_14 = QtWidgets.QLabel(self.centralwidget)
                self.label_14.setGeometry(QtCore.QRect(100, 520, 101, 31))
                self.label_14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
        "border-radius:20px;")
                self.label_14.setObjectName("label_14")
                self.label_15 = QtWidgets.QLabel(self.centralwidget)
                self.label_15.setGeometry(QtCore.QRect(60, 580, 271, 41))
                font = QtGui.QFont()
                font.setFamily("Verdana")
                font.setPointSize(25)
                font.setBold(True)
                font.setWeight(75)
                self.label_15.setFont(font)
                self.label_15.setObjectName("label_15")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.clicked.connect(self.bukaDetailVip)

                self.pushButton_2.setGeometry(QtCore.QRect(60, 690, 261, 41))
                self.pushButton_2.setStyleSheet("QPushButton#pushButton_2 {\n"
        "    background-color: transparent; /* Background clear */\n"
        "    color: rgba(255, 255, 255, 255); \n"
        "    border: 2px solid rgba(255, 255, 255, 180); /* Border putih transparan */\n"
        "    border-radius: 8px;\n"
        "    padding: 10px 25px;\n"
        "    font-size: 14px;\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "/* Hover: border lebih terang + sedikit glow */\n"
        "QPushButton#pushButton_2:hover {\n"
        "    background-color: rgba(255, 255, 255, 20); /* Transparan tipis */\n"
        "    border: 2px solid rgba(255, 255, 255, 220);\n"
        "}\n"
        "\n"
        "/* Pressed: background berubah jadi GRADIENT biru */\n"
        "QPushButton#pushButton_2:pressed {\n"
        "    background-color: qlineargradient(\n"
        "        spread:pad, \n"
        "        x1:0, y1:0.505682, \n"
        "        x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219),   /* Biru tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)   /* Biru abu */\n"
        "    );\n"
        "    border: 2px solid rgba(255, 255, 255, 255); /* Border tetap putih */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "}\n"
        "")
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_4.clicked.connect(self.bukapembayaranvip)
                self.pushButton_4.setGeometry(QtCore.QRect(330, 690, 151, 41))
                self.pushButton_4.setStyleSheet("QPushButton#pushButton_4 {\n"
        "    /* Background Gradient Default */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219), /* Biru Tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)); /* Abu-abu Kebiruan */\n"
        "        \n"
        "    color: rgba(255, 255, 255, 255); /* Teks Putih Solid (lebih jelas) */\n"
        "    border-radius: 8px; /* Menggunakan 8px agar konsisten dengan elemen lain */\n"
        "    border: none; /* Pastikan tidak ada border bawaan */\n"
        "    padding: 10px 25px; /* Padding untuk tombol agar terlihat tebal */\n"
        "    font-size: 14px; /* Ukuran font yang konsisten */\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton#pushButton_4:hover {\n"
        "    /* Gradient Hover: Warna sedikit lebih cerah/kontras */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(40, 67, 98, 219), /* Biru Tua Sedikit Cerah */\n"
        "        stop:1 rgba(105, 118, 132, 226)); /* Abu-abu Kebiruan Sedikit Cerah */\n"
        "}\n"
        "\n"
        "QPushButton#pushButton_4:pressed {\n"
        "    /* Efek Pressed (Tombol Tertekan) */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    /* Memberikan ilusi tombol bergerak ke dalam */\n"
        "    background-color: rgba(105, 118, 132, 255); /* Warna solid yang lebih gelap/tertarik */\n"
        "    border-style: inset; /* Opsi lain: inset border */\n"
        "}")
                self.pushButton_4.setObjectName("pushButton_4")
                self.label_17 = QtWidgets.QLabel(self.centralwidget)
                self.label_17.setGeometry(QtCore.QRect(340, 580, 171, 41))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(19)
                font.setBold(True)
                font.setWeight(75)
                self.label_17.setFont(font)
                self.label_17.setStyleSheet("color: rgba(140, 100, 70, 1);\n"
        "")
                self.label_17.setObjectName("label_17")
                self.label_18 = QtWidgets.QLabel(self.centralwidget)
                self.label_18.setGeometry(QtCore.QRect(530, 710, 101, 31))
                self.label_18.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
        "border-radius:20px;")
                self.label_18.setObjectName("label_18")
                self.label_19 = QtWidgets.QLabel(self.centralwidget)
                self.label_19.setGeometry(QtCore.QRect(220, 770, 271, 41))
                font = QtGui.QFont()
                font.setFamily("Verdana")
                font.setPointSize(25)
                font.setBold(True)
                font.setWeight(75)
                self.label_19.setFont(font)
                self.label_19.setObjectName("label_19")
                self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_5.clicked.connect(self.bukaDetailVvip)

                self.pushButton_5.setGeometry(QtCore.QRect(230, 900, 251, 41))
                self.pushButton_5.setStyleSheet("QPushButton#pushButton_5 {\n"
        "    background-color: transparent; /* Background clear */\n"
        "    color: rgba(255, 255, 255, 255); \n"
        "    border: 2px solid rgba(255, 255, 255, 180); /* Border putih transparan */\n"
        "    border-radius: 8px;\n"
        "    padding: 10px 25px;\n"
        "    font-size: 14px;\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "/* Hover: border lebih terang + sedikit glow */\n"
        "QPushButton#pushButton_5:hover {\n"
        "    background-color: rgba(255, 255, 255, 20); /* Transparan tipis */\n"
        "    border: 2px solid rgba(255, 255, 255, 220);\n"
        "}\n"
        "\n"
        "/* Pressed: background berubah jadi GRADIENT biru */\n"
        "QPushButton#pushButton_5:pressed {\n"
        "    background-color: qlineargradient(\n"
        "        spread:pad, \n"
        "        x1:0, y1:0.505682, \n"
        "        x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219),   /* Biru tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)   /* Biru abu */\n"
        "    );\n"
        "    border: 2px solid rgba(255, 255, 255, 255); /* Border tetap putih */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "}\n"
        "")
                self.pushButton_5.setObjectName("pushButton_5")
                self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_6.clicked.connect(self.bukapembayaranvvip)
                self.pushButton_6.setGeometry(QtCore.QRect(490, 900, 171, 41))
                self.pushButton_6.setStyleSheet("QPushButton#pushButton_6 {\n"
        "    /* Background Gradient Default */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219), /* Biru Tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)); /* Abu-abu Kebiruan */\n"
        "        \n"
        "    color: rgba(255, 255, 255, 255); /* Teks Putih Solid (lebih jelas) */\n"
        "    border-radius: 8px; /* Menggunakan 8px agar konsisten dengan elemen lain */\n"
        "    border: none; /* Pastikan tidak ada border bawaan */\n"
        "    padding: 10px 25px; /* Padding untuk tombol agar terlihat tebal */\n"
        "    font-size: 14px; /* Ukuran font yang konsisten */\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton#pushButton_6:hover {\n"
        "    /* Gradient Hover: Warna sedikit lebih cerah/kontras */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(40, 67, 98, 219), /* Biru Tua Sedikit Cerah */\n"
        "        stop:1 rgba(105, 118, 132, 226)); /* Abu-abu Kebiruan Sedikit Cerah */\n"
        "}\n"
        "\n"
        "QPushButton#pushButton_6:pressed {\n"
        "    /* Efek Pressed (Tombol Tertekan) */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    /* Memberikan ilusi tombol bergerak ke dalam */\n"
        "    background-color: rgba(105, 118, 132, 255); /* Warna solid yang lebih gelap/tertarik */\n"
        "    border-style: inset; /* Opsi lain: inset border */\n"
        "}")
                self.pushButton_6.setObjectName("pushButton_6")
                self.label_21 = QtWidgets.QLabel(self.centralwidget)
                self.label_21.setGeometry(QtCore.QRect(460, 770, 201, 51))
                font = QtGui.QFont()
                font.setFamily("Verdana")
                font.setPointSize(19)
                font.setBold(True)
                font.setWeight(75)
                self.label_21.setFont(font)
                self.label_21.setStyleSheet("color: rgba(140, 100, 70, 1);\n"
        "")
                self.label_21.setObjectName("label_21")
                self.label_12 = QtWidgets.QLabel(self.centralwidget)
                self.label_12.setGeometry(QtCore.QRect(100, 920, 91, 16))
                self.label_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
        "border-radius:20px;")
                self.label_12.setObjectName("label_12")
                self.label_20 = QtWidgets.QLabel(self.centralwidget)
                self.label_20.setGeometry(QtCore.QRect(130, 380, 61, 20))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(10)
                self.label_20.setFont(font)
                self.label_20.setStyleSheet("color: rgba(255,255,255,230);  /* Putih */\n"
        "background-color: qlineargradient(\n"
        "    spread:pad,\n"
        "    x1:0, y1:0,\n"
        "    x2:0, y2:0.715909,\n"
        "    stop:0 rgba(180, 170, 150, 255),\n"
        "    stop:0.5 rgba(160, 150, 135, 255),\n"
        "    stop:1 rgba(130, 120, 105, 255)\n"
        ");\n"
        "\n"
        "")
                self.label_20.setObjectName("label_20")
                self.label_22 = QtWidgets.QLabel(self.centralwidget)
                self.label_22.setGeometry(QtCore.QRect(620, 420, 61, 21))
                self.label_22.setObjectName("label_22")
                self.label_23 = QtWidgets.QLabel(self.centralwidget)
                self.label_23.setGeometry(QtCore.QRect(240, 440, 421, 31))
                self.label_23.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 9pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_23.setObjectName("label_23")
                self.label_16 = QtWidgets.QLabel(self.centralwidget)
                self.label_16.setGeometry(QtCore.QRect(280, 220, 141, 61))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(8)
                font.setBold(True)
                font.setWeight(75)
                self.label_16.setFont(font)
                self.label_16.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt; \n"
        "   font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_16.setObjectName("label_16")
                self.label_24 = QtWidgets.QLabel(self.centralwidget)
                self.label_24.setGeometry(QtCore.QRect(130, 220, 141, 61))
                self.label_24.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt; \n"
        " font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_24.setObjectName("label_24")
                self.label_25 = QtWidgets.QLabel(self.centralwidget)
                self.label_25.setGeometry(QtCore.QRect(430, 220, 131, 61))
                self.label_25.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt;\n"
        " font-weight: bold;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_25.setObjectName("label_25")
                self.label_26 = QtWidgets.QLabel(self.centralwidget)
                self.label_26.setGeometry(QtCore.QRect(440, 620, 54, 14))
                self.label_26.setObjectName("label_26")
                self.label_27 = QtWidgets.QLabel(self.centralwidget)
                self.label_27.setGeometry(QtCore.QRect(540, 570, 61, 16))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(10)
                self.label_27.setFont(font)
                self.label_27.setStyleSheet("color: rgba(255,255,255,230);  /* Putih */\n"
        "background-color: qlineargradient(\n"
        "    spread:pad,\n"
        "    x1:0, y1:0,\n"
        "    x2:0, y2:0.715909,\n"
        "    stop:0 rgba(180, 170, 150, 255),\n"
        "    stop:0.5 rgba(160, 150, 135, 255),\n"
        "    stop:1 rgba(130, 120, 105, 255)\n"
        ");")
                self.label_27.setObjectName("label_27")
                self.label_28 = QtWidgets.QLabel(self.centralwidget)
                self.label_28.setGeometry(QtCore.QRect(70, 640, 421, 31))
                self.label_28.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 9pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_28.setObjectName("label_28")
                self.label_29 = QtWidgets.QLabel(self.centralwidget)
                self.label_29.setGeometry(QtCore.QRect(113, 770, 71, 20))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(10)
                self.label_29.setFont(font)
                self.label_29.setStyleSheet("color: rgba(255,255,255,230);  /* Putih */\n"
        "background-color: qlineargradient(\n"
        "    spread:pad,\n"
        "    x1:0, y1:0,\n"
        "    x2:0, y2:0.715909,\n"
        "    stop:0 rgba(180, 170, 150, 255),\n"
        "    stop:0.5 rgba(160, 150, 135, 255),\n"
        "    stop:1 rgba(130, 120, 105, 255)\n"
        ");\n"
        "")
                self.label_29.setObjectName("label_29")
                self.label_30 = QtWidgets.QLabel(self.centralwidget)
                self.label_30.setGeometry(QtCore.QRect(610, 820, 54, 14))
                self.label_30.setObjectName("label_30")
                self.label_31 = QtWidgets.QLabel(self.centralwidget)
                self.label_31.setGeometry(QtCore.QRect(240, 850, 421, 31))
                self.label_31.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_31.setObjectName("label_31")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 22))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.pushButton.setText(_translate("MainWindow", "CARI "))
                self.label_13.setText(_translate("MainWindow", "Rp450.000 "))
                self.detailButton_2.setText(_translate("MainWindow", "Detail Kamar "))
                self.label_11.setText(_translate("MainWindow", "KOS BIASA "))
                self.pushButton_3.setText(_translate("MainWindow", "Pesan "))
                self.detailButton_8.setText(_translate("MainWindow", "Kembali"))
                self.label_9.setText(_translate("MainWindow", "Tipe - Tipe Kamar"))
                self.label_10.setText(_translate("MainWindow", "Yuk Pilih Kamar!"))
                self.label_6.setText(_translate("MainWindow", "✨ KOS MEWAH ✨"))
                self.label_14.setText(_translate("MainWindow", "⭐️⭐️⭐️⭐️⭐️"))
                self.label_15.setText(_translate("MainWindow", "KOS VIP"))
                self.pushButton_2.setText(_translate("MainWindow", "Detail Kamar"))
                self.pushButton_4.setText(_translate("MainWindow", "Pesan"))
                self.label_17.setText(_translate("MainWindow", "Rp750.000 "))
                self.label_18.setText(_translate("MainWindow", "⭐️⭐️⭐️⭐️⭐️"))
                self.label_19.setText(_translate("MainWindow", "KOS VVIP"))
                self.pushButton_5.setText(_translate("MainWindow", "Detail Kamar"))
                self.pushButton_6.setText(_translate("MainWindow", "Pesan"))
                self.label_21.setText(_translate("MainWindow", "Rp1.200.000"))
                self.label_12.setText(_translate("MainWindow", "⭐️⭐️⭐️⭐️⭐️"))
                self.label_20.setText(_translate("MainWindow", "Tersedia"))
                self.label_22.setText(_translate("MainWindow", "/ bulan"))
                self.label_23.setText(_translate("MainWindow", "👤 1 Guest     🛏️1 Bed        🚽Km Luar   💨free Kipas"))
                self.label_16.setText(_translate("MainWindow", "         🔒\n"
        "Keamanan 24/7"))
                self.label_24.setText(_translate("MainWindow", "          📶\n"
        "WiFi Super Cepat"))
                self.label_25.setText(_translate("MainWindow", "          📍\n"
        "Lokasi Strategis"))
                self.label_26.setText(_translate("MainWindow", "/ bulan"))
                self.label_27.setText(_translate("MainWindow", "Tersedia"))
                self.label_28.setText(_translate("MainWindow", "👤1 Guest    🛏️ 1 Bed        🚽Km Dalam   💨free Kipas"))
                self.label_29.setText(_translate("MainWindow", "Tersedia"))
                self.label_30.setText(_translate("MainWindow", " / bulan"))
                self.label_31.setText(_translate("MainWindow", "👤1 Guest   🛏️1 King Bed     🚽Km Dalam    🌡️AC"))

        
        def bukaDetailBiasa(self):
                from detailkamarbiasa import Ui_MainWindow as Ui_DetailKamarBiasa  # IMPORT DI DALAM FUNGSI

                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_DetailKamarBiasa()
                self.ui.setupUi(self.window)
                self.window.show()
                self.MainWindow.close()

        
        def bukaDetailVip(self):
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_DetailKamarVip()
                self.ui.setupUi(self.window)
                self.window.show()
                self.MainWindow.close()

        def bukaDetailVvip(self):
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_DetailKamarVvip()
                self.ui.setupUi(self.window)
                self.window.show()
                self.MainWindow.close()

        def ui_bukapembayaranbiasa(self):
                # CEK LOGIN DULU!
                if not user.is_logged_in:
                        QMessageBox.warning(None, "Login Dulu", "Anda harus login untuk memesan kamar!")

                        # Buka halaman login
                        self.MainWindow.close()
                        self.window = QtWidgets.QMainWindow()
                        self.login = LoginUI()
                        self.login.setupUi(self.window)
                        self.window.show()
                        return  # STOP di sini supaya tidak lanjut ke pembayaran

                # --- Jika sudah login, buka halaman pembayaran ---
                self.window = QtWidgets.QMainWindow()
                self.ui_pembayaran = Ui_Pembayarankosbiasa()
                
                self.ui_pembayaran.setupUi(self.window)
                self.window.show()


        
        def bukapembayaranvip(self):
                # CEK LOGIN DULU!
                if not user.is_logged_in:
                        QMessageBox.warning(None, "Login Dulu", "Anda harus login untuk memesan kamar!")

                        # Buka halaman login
                        self.MainWindow.close()
                        self.window = QtWidgets.QMainWindow()
                        self.login = LoginUI()
                        self.login.setupUi(self.window)
                        self.window.show()
                        return  # STOP di sini supaya tidak lanjut ke pembayaran

                # --- Jika sudah login, buka halaman pembayaran ---
                self.window = QtWidgets.QMainWindow()
                self.ui_pembayaran = Ui_Pembayarankosvip()
                self.ui_pembayaran.setupUi(self.window)
                self.window.show()
        

        
        def bukapembayaranvvip(self):
                # CEK LOGIN DULU!
                if not user.is_logged_in:
                        QMessageBox.warning(None, "Login Dulu", "Anda harus login untuk memesan kamar!")

                        # Buka halaman login
                        self.MainWindow.close()
                        self.window = QtWidgets.QMainWindow()
                        self.login = LoginUI()
                        self.login.setupUi(self.window)
                        self.window.show()
                        return  # STOP di sini supaya tidak lanjut ke pembayaran

                # --- Jika sudah login, buka halaman pembayaran ---
                self.window = QtWidgets.QMainWindow()
                self.ui_pembayaran = Ui_Pembayarankosvvip()
                self.ui_pembayaran.setupUi(self.window)
                self.window.show()

        

        def cariKamar(self):
                keyword = self.lineEdit.text().lower().strip()


                # Buka halaman sesuai keyword
                if keyword == "biasa":
                        self.MainWindow.close()
                        self.bukaDetailBiasa()
                        return

                elif keyword == "vip":
                        self.MainWindow.close()
                        self.bukaDetailVip()
                        return

                elif keyword == "vvip":
                        self.MainWindow.close()
                        self.bukaDetailVvip()
                        return

                # Jika keyword tidak dikenal
                QMessageBox.warning(None, "Tidak ditemukan", f"Kamar '{keyword}' tidak ada.")


        
        def kembali(self):
                if self.role == "pengguna":
                        from dashboardpenghuni import Ui_MainWindow as Dashboard
                        self.window = QtWidgets.QMainWindow()
                        self.ui = Dashboard()
                        self.ui.setupUi(self.window)
                        self.window.show()
                else:
                        from login import Ui_MainWindow as Login
                        self.window = QtWidgets.QMainWindow()
                        self.ui = Login()
                        self.ui.setupUi(self.window)
                        self.window.show()

                self.MainWindow.close()










                        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
