# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboardadmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dashboardadmin_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 351, 461))
        self.label.setStyleSheet("border-image: url(:/dashboardadmin/Foto/bg.jpg);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(69, 50, 311, 411))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.labelDashboardAdmin = QtWidgets.QLabel(self.centralwidget)
        self.labelDashboardAdmin.setGeometry(QtCore.QRect(90, 90, 271, 24))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelDashboardAdmin.setFont(font)
        self.labelDashboardAdmin.setStyleSheet("color:rgba(255,255,255,210);")
        self.labelDashboardAdmin.setObjectName("labelDashboardAdmin")
        self.pushButtonDataKamar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDataKamar.setGeometry(QtCore.QRect(143, 140, 175, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDataKamar.setFont(font)
        self.pushButtonDataKamar.setStyleSheet("/* Style untuk tombol menu utama */\n"
"QPushButton#pushButtonDataKamar,\n"
"QPushButton#pushButtonDataPenghuni, \n"
"QPushButton#pushButtonLaporan,\n"
"QPushButton#pushButtonValidasiPembayaran,\n"
"QPushButton#pushButtonLogout {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Efek hover untuk tombol menu */\n"
"QPushButton#pushButtonDataKamar:hover,\n"
"QPushButton#pushButtonDataPenghuni:hover,\n"
"QPushButton#pushButtonLaporan:hover,\n"
"QPushButton#pushButtonValidasiPembayaran:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"/* Efek hover untuk tombol logout */\n"
"QPushButton#pushButtonLogout:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"/* Efek pressed untuk semua tombol */\n"
"QPushButton#pushButtonDataKamar:pressed,\n"
"QPushButton#pushButtonDataPenghuni:pressed,\n"
"QPushButton#pushButtonLaporan:pressed,\n"
"QPushButton#pushButtonValidasiPembayaran:pressed,\n"
"QPushButton#pushButtonLogout:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(105, 118, 132, 200);\n"
"}")
        self.pushButtonDataKamar.setObjectName("pushButtonDataKamar")
        self.pushButtonDataPenghuni = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDataPenghuni.setGeometry(QtCore.QRect(143, 200, 175, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDataPenghuni.setFont(font)
        self.pushButtonDataPenghuni.setStyleSheet("/* Style untuk tombol menu utama */\n"
"QPushButton#pushButtonDataKamar,\n"
"QPushButton#pushButtonDataPenghuni, \n"
"QPushButton#pushButtonLaporan,\n"
"QPushButton#pushButtonValidasiPembayaran,\n"
"QPushButton#pushButtonLogout {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Efek hover untuk tombol menu */\n"
"QPushButton#pushButtonDataKamar:hover,\n"
"QPushButton#pushButtonDataPenghuni:hover,\n"
"QPushButton#pushButtonLaporan:hover,\n"
"QPushButton#pushButtonValidasiPembayaran:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"/* Efek hover untuk tombol logout */\n"
"QPushButton#pushButtonLogout:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"/* Efek pressed untuk semua tombol */\n"
"QPushButton#pushButtonDataKamar:pressed,\n"
"QPushButton#pushButtonDataPenghuni:pressed,\n"
"QPushButton#pushButtonLaporan:pressed,\n"
"QPushButton#pushButtonValidasiPembayaran:pressed,\n"
"QPushButton#pushButtonLogout:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(105, 118, 132, 200);\n"
"}")
        self.pushButtonDataPenghuni.setObjectName("pushButtonDataPenghuni")
        self.pushButtonLogout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLogout.setGeometry(QtCore.QRect(143, 380, 175, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogout.setFont(font)
        self.pushButtonLogout.setStyleSheet("/* Style untuk tombol menu utama */\n"
"QPushButton#pushButtonDataKamar,\n"
"QPushButton#pushButtonDataPenghuni, \n"
"QPushButton#pushButtonLaporan,\n"
"QPushButton#pushButtonValidasiPembayaran,\n"
"QPushButton#pushButtonLogout {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Efek hover untuk tombol menu */\n"
"QPushButton#pushButtonDataKamar:hover,\n"
"QPushButton#pushButtonDataPenghuni:hover,\n"
"QPushButton#pushButtonLaporan:hover,\n"
"QPushButton#pushButtonValidasiPembayaran:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"/* Efek hover untuk tombol logout */\n"
"QPushButton#pushButtonLogout:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"/* Efek pressed untuk semua tombol */\n"
"QPushButton#pushButtonDataKamar:pressed,\n"
"QPushButton#pushButtonDataPenghuni:pressed,\n"
"QPushButton#pushButtonLaporan:pressed,\n"
"QPushButton#pushButtonValidasiPembayaran:pressed,\n"
"QPushButton#pushButtonLogout:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(105, 118, 132, 200);\n"
"}")
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.pushButtonLaporan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLaporan.setGeometry(QtCore.QRect(143, 260, 175, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLaporan.setFont(font)
        self.pushButtonLaporan.setStyleSheet("/* Style untuk tombol menu utama */\n"
"QPushButton#pushButtonDataKamar,\n"
"QPushButton#pushButtonDataPenghuni, \n"
"QPushButton#pushButtonLaporan,\n"
"QPushButton#pushButtonValidasiPembayaran,\n"
"QPushButton#pushButtonLogout {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Efek hover untuk tombol menu */\n"
"QPushButton#pushButtonDataKamar:hover,\n"
"QPushButton#pushButtonDataPenghuni:hover,\n"
"QPushButton#pushButtonLaporan:hover,\n"
"QPushButton#pushButtonValidasiPembayaran:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"/* Efek hover untuk tombol logout */\n"
"QPushButton#pushButtonLogout:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"/* Efek pressed untuk semua tombol */\n"
"QPushButton#pushButtonDataKamar:pressed,\n"
"QPushButton#pushButtonDataPenghuni:pressed,\n"
"QPushButton#pushButtonLaporan:pressed,\n"
"QPushButton#pushButtonValidasiPembayaran:pressed,\n"
"QPushButton#pushButtonLogout:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(105, 118, 132, 200);\n"
"}")
        self.pushButtonLaporan.setObjectName("pushButtonLaporan")
        self.pushButtonPembayaran = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPembayaran.setGeometry(QtCore.QRect(140, 320, 175, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPembayaran.setFont(font)
        self.pushButtonPembayaran.setStyleSheet("QPushButton#pushButtonPembayaran {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#pushButtonPembayaran:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"\n"
"QPushButton#pushButtonPembayaran:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(105, 118, 132, 200);\n"
"}\n"
"")
        self.pushButtonPembayaran.setObjectName("pushButtonPembayaran")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelDashboardAdmin.setText(_translate("MainWindow", "Dashboard Admin"))
        self.pushButtonDataKamar.setText(_translate("MainWindow", "Data Kamar"))
        self.pushButtonDataPenghuni.setText(_translate("MainWindow", "Data Penghuni"))
        self.pushButtonLogout.setText(_translate("MainWindow", "Logout"))
        self.pushButtonLaporan.setText(_translate("MainWindow", "Laporan"))
        self.pushButtonPembayaran.setText(_translate("MainWindow", "Pembayaran"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
