# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboardpenghuni.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dashboardpenghuni_rc
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                self.MainWindow = MainWindow

                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(543, 700)
                
                MainWindow.setStyleSheet("QMainWindow {\n"
        "    background-color: #ffffff;\n"
        "}\n"
        "\n"
        "QWidget#centralwidget {\n"
        "    background: transparent;\n"
        "}\n"
        "\n"
        "QFrame#dashboardFrame {\n"
        "    background: rgba(50, 70, 90, 0.95);\n"
        "    border-radius: 25px;\n"
        "    border: 2px solid rgba(100, 120, 140, 0.5);\n"
        "}\n"
        "\n"
        "QLabel#titleLabel {\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    font-size: 30px;\n"
        "    font-weight: bold;\n"
        "    text-shadow: 3px 3px 6px rgba(0, 0, 0, 0.8);\n"
        "    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
        "                stop:0 rgba(20, 47, 78, 200), stop:1 rgba(85, 98, 112, 200));\n"
        "    border-radius: 12px;\n"
        "    padding: 12px 25px;\n"
        "    border: 1px solid rgba(255, 255, 255, 0.3);\n"
        "}\n"
        "\n"
        "QFrame#imageFrame {\n"
        "    background: rgba(255, 255, 255, 0.95);\n"
        "    border-radius: 18px;\n"
        "    border: 3px solid rgba(255, 255, 255, 0.6);\n"
        "}\n"
        "\n"
        "QLabel#imageLabel {\n"
        "    background-color: #f5f5f5;\n"
        "    border-radius: 15px;\n"
        "}\n"
        "\n"
        "QLabel#roomLabel {\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    font-size: 16px;\n"
        "    font-weight: bold;\n"
        "    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
        "                stop:0 rgba(20, 47, 78, 180), stop:1 rgba(85, 98, 112, 180));\n"
        "    border-radius: 10px;\n"
        "    padding: 10px 25px;\n"
        "    border: 1px solid rgba(255, 255, 255, 0.25);\n"
        "}\n"
        "\n"
        "QPushButton#kosButton {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "                      stop:0 rgba(240, 240, 240, 230), stop:1 rgba(255, 255, 255, 240));\n"
        "    color: rgba(30, 30, 30, 255);\n"
        "    border: 2px solid rgba(255, 255, 255, 0.6);\n"
        "    border-radius: 10px;\n"
        "    padding: 14px 35px;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton#kosButton:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "                      stop:0 rgba(255, 255, 255, 240), stop:1 rgba(255, 255, 255, 255));\n"
        "}\n"
        "\n"
        "QPushButton#kosButton:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(220, 220, 220, 230);\n"
        "}\n"
        "\n"
        "QPushButton#accountButton {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "                      stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 10px;\n"
        "    padding: 14px 35px;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "    border: 2px solid rgba(255, 255, 255, 0.15);\n"
        "}\n"
        "\n"
        "QPushButton#accountButton:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "                      stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#accountButton:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setSpacing(0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout()
                self.verticalLayout_2.setSpacing(0)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_2.addItem(spacerItem)
                self.horizontalLayout = QtWidgets.QHBoxLayout()
                self.horizontalLayout.setObjectName("horizontalLayout")
                spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout.addItem(spacerItem1)
                self.dashboardFrame = QtWidgets.QFrame(self.centralwidget)
                self.dashboardFrame.setMinimumSize(QtCore.QSize(380, 480))
                self.dashboardFrame.setMaximumSize(QtCore.QSize(450, 550))
                self.dashboardFrame.setObjectName("dashboardFrame")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dashboardFrame)
                self.verticalLayout_3.setContentsMargins(35, 35, 35, 35)
                self.verticalLayout_3.setSpacing(25)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.titleLabel = QtWidgets.QLabel(self.dashboardFrame)
                font = QtGui.QFont()
                font.setFamily("MS Reference Sans Serif")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.titleLabel.setFont(font)
                self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.titleLabel.setObjectName("titleLabel")
                self.verticalLayout_3.addWidget(self.titleLabel)
                self.imageLabel = QtWidgets.QLabel(self.dashboardFrame)
                self.imageLabel.setMinimumSize(QtCore.QSize(250, 250))
                self.imageLabel.setStyleSheet("padding : 13px;\n"
        "border-image: url(:/dasbordpenghuni/Foto/penghuni.jpeg);\n"
        "")
                self.imageLabel.setText("")
                self.imageLabel.setPixmap(QtGui.QPixmap(":/Desain Kost Tropis.jpeg"))
                self.imageLabel.setScaledContents(True)
                self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.imageLabel.setObjectName("imageLabel")
                self.verticalLayout_3.addWidget(self.imageLabel)
                self.roomLabel = QtWidgets.QLabel(self.dashboardFrame)
                font = QtGui.QFont()
                font.setFamily("Segoe Script")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.roomLabel.setFont(font)
                self.roomLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.roomLabel.setObjectName("roomLabel")
                self.verticalLayout_3.addWidget(self.roomLabel)
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_2.setSpacing(20)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.kosButton = QtWidgets.QPushButton(self.dashboardFrame)
                self.kosButton.clicked.connect(self.bukacarikamar)
                font = QtGui.QFont()
                font.setFamily("Palatino Linotype")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.kosButton.setFont(font)
                self.kosButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.kosButton.setObjectName("kosButton")
                self.horizontalLayout_2.addWidget(self.kosButton)
                self.accountButton = QtWidgets.QPushButton(self.dashboardFrame)
                font = QtGui.QFont()
                font.setFamily("Palatino Linotype")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.accountButton.setFont(font)
                self.accountButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.accountButton.setObjectName("accountButton")
                self.horizontalLayout_2.addWidget(self.accountButton)
                self.verticalLayout_3.addLayout(self.horizontalLayout_2)
                self.horizontalLayout.addWidget(self.dashboardFrame)
                spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout.addItem(spacerItem2)
                self.verticalLayout_2.addLayout(self.horizontalLayout)
                spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_2.addItem(spacerItem3)
                self.verticalLayout.addLayout(self.verticalLayout_2)
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)
                # ========== TOMBOL LOGOUT DI POJOK KIRI ATAS ==========
                # ========== TOMBOL LOGOUT DI POJOK KIRI ATAS ==========
                self.logoutButton = QtWidgets.QPushButton(self.dashboardFrame)
                self.logoutButton.setObjectName("logoutButton")
                self.logoutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.logoutButton.setText("Logout")

                # Style mengikuti tombol lain (accountButton)
                self.logoutButton.setStyleSheet("""
                QPushButton#logoutButton {
                background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,
                        stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));
                color: rgba(255, 255, 255, 210);
                border-radius: 10px;
                padding: 5px 15px;
                font-size: 13px;
                font-weight: bold;
                border: 2px solid rgba(255, 255, 255, 0.15);
                }
                QPushButton#logoutButton:hover {
                background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,
                        stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));
                }
                QPushButton#logoutButton:pressed {
                padding-left: 5px;
                padding-top: 5px;
                background-color: rgba(105, 118, 132, 200);
                }
                """)

                # POSISI BARU DI DALAM DASHBOARDFRAME
                self.logoutButton.move(10, 10)
                self.logoutButton.setFixedSize(90, 30)

                # Connect tombol logout
                self.logoutButton.clicked.connect(self.logout)



        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard Penghuni"))
                self.titleLabel.setText(_translate("MainWindow", "Dashboard Penghuni"))
                self.roomLabel.setText(_translate("MainWindow", "~Selamat datang di Kos Mewah~"))
                self.kosButton.setText(_translate("MainWindow", "Kos Mewah"))
                self.accountButton.setText(_translate("MainWindow", "Akun"))

        """def bukacarikamar(self):
                self.window = QtWidgets.QMainWindow()
                self.ui = ui_bukacarikamar()
                self.ui.setupUi(self.window)
                self.window.show()
                self.MainWindow.close()"""

        def bukacarikamar(self):
                from carikamar import Ui_MainWindow as CariKamar

                self.window = QtWidgets.QMainWindow()
                self.ui = CariKamar()
                self.ui.setupUi(self.window, role="pengguna")
                self.window.show()
                self.MainWindow.close()

        def logout(self):
                from login import Ui_MainWindow as LoginUI
                import user  # kalau pakai modul user

                # Reset status login
                user.is_logged_in = False

                QMessageBox.information(None, "Logout", "Anda berhasil logout!")

                # Buka halaman login
                self.loginWindow = QtWidgets.QMainWindow()
                self.loginUI = LoginUI()
                self.loginUI.setupUi(self.loginWindow)
                self.loginWindow.show()

                # Tutup dashboard
                self.MainWindow.close()







if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

