# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datapenghuni.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datapenghuni_rc
import connection
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1147, 692)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(50, 30, 721, 461))
                self.label.setStyleSheet("border-image: url(:/foto/C:/Users/DIMAS/Downloads/Gambar WhatsApp 2025-11-21 pukul 12.18.08_2e6410ed.jpg);")
                self.label.setText("")
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(69, 50, 1041, 501))
                self.label_2.setStyleSheet("border-image: url(:/datapenghuni/Foto/bg.jpg);\n"
        "border-radius:20px;")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.labelDataPenghuni = QtWidgets.QLabel(self.centralwidget)
                self.labelDataPenghuni.setGeometry(QtCore.QRect(520, 80, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.labelDataPenghuni.setFont(font)
                self.labelDataPenghuni.setStyleSheet("color:rgba(255,255,255,210);")
                self.labelDataPenghuni.setObjectName("labelDataPenghuni")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(140, 120, 901, 51))
                self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
        "border-radius:10px;")
                self.label_4.setText("")
                self.label_4.setObjectName("label_4")
                self.lineEditCari = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEditCari.setGeometry(QtCore.QRect(155, 134, 221, 31))
                self.lineEditCari.setStyleSheet("border-radius:10px;")
                self.lineEditCari.setObjectName("lineEditCari")
                self.pushButtonTambah = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonTambah.setGeometry(QtCore.QRect(470, 130, 121, 31))
                self.pushButtonTambah.setStyleSheet("/* Style untuk tombol tambah */\n"
        "QPushButton#pushButtonTambah {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonTambah:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonTambah:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}")
                self.pushButtonTambah.setObjectName("pushButtonTambah")
                self.pushButtonEdit = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonEdit.setGeometry(QtCore.QRect(620, 130, 121, 31))
                self.pushButtonEdit.setStyleSheet("/* Style untuk tombol edit */\n"
        "QPushButton#pushButtonEdit {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonEdit:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonEdit:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}")
                self.pushButtonEdit.setObjectName("pushButtonEdit")
                self.pushButtonRefresh = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonRefresh.setGeometry(QtCore.QRect(920, 130, 100, 31))
                self.pushButtonRefresh.setStyleSheet("/* Style untuk tombol hapus */\n"
        "QPushButton#pushButtonRefresh {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonRefresh:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonRefresh:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}")
                self.pushButtonRefresh.setObjectName("pushButtonRefresh")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(80, 70, 1021, 451))
                self.label_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
        "border-radius:20px;")
                self.label_5.setText("")
                self.label_5.setObjectName("label_5")
                self.tableWidgetTabel = QtWidgets.QTableWidget(self.centralwidget)
                self.tableWidgetTabel.setGeometry(QtCore.QRect(120, 190, 951, 311))
                self.tableWidgetTabel.setMinimumSize(QtCore.QSize(256, 192))
                self.tableWidgetTabel.setStyleSheet("border-radius: 5px;\n"
        "")
                self.tableWidgetTabel.setObjectName("tableWidgetTabel")
                self.tableWidgetTabel.setColumnCount(12)
                self.tableWidgetTabel.setRowCount(0)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(5, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(6, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(7, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(8, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(9, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(10, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidgetTabel.setHorizontalHeaderItem(11, item)
                self.pushButtonKembali = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonKembali.setGeometry(QtCore.QRect(550, 580, 141, 31))
                self.pushButtonKembali.setStyleSheet("/* Style untuk tombol kembali */\n"
        "QPushButton#pushButtonKembali {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonKembali:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonKembali:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}")
                self.pushButtonKembali.setObjectName("pushButtonKembali")
                self.pushButtonCari = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonCari.setGeometry(QtCore.QRect(380, 130, 71, 31))
                self.pushButtonCari.setStyleSheet("/* Style untuk tombol cari */\n"
        "QPushButton#pushButtonCari {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonCari:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonCari:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}")
                self.pushButtonCari.setObjectName("pushButtonCari")
                self.pushButtonHapus = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonHapus.setGeometry(QtCore.QRect(780, 130, 100, 31))
                self.pushButtonHapus.setStyleSheet("/* Style untuk tombol hapus */\n"
        "QPushButton#pushButtonHapus {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonHapus:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonHapus:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}")
                self.pushButtonHapus.setObjectName("pushButtonHapus")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1147, 23))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.load_data()

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.labelDataPenghuni.setText(_translate("MainWindow", "Data Penghuni"))
                self.lineEditCari.setText(_translate("MainWindow", "Cari"))
                self.pushButtonTambah.setText(_translate("MainWindow", "Tambah"))
                self.pushButtonEdit.setText(_translate("MainWindow", "Edit"))
                self.pushButtonRefresh.setText(_translate("MainWindow", "Refresh"))
                item = self.tableWidgetTabel.horizontalHeaderItem(0)
                item.setText(_translate("MainWindow", "ID"))
                item = self.tableWidgetTabel.horizontalHeaderItem(1)
                item.setText(_translate("MainWindow", "Nama"))
                item = self.tableWidgetTabel.horizontalHeaderItem(2)
                item.setText(_translate("MainWindow", "Nama Lengkap"))
                item = self.tableWidgetTabel.horizontalHeaderItem(3)
                item.setText(_translate("MainWindow", "Telepon"))
                item = self.tableWidgetTabel.horizontalHeaderItem(4)
                item.setText(_translate("MainWindow", "Nomor kamar"))
                item = self.tableWidgetTabel.horizontalHeaderItem(5)
                item.setText(_translate("MainWindow", "Kategori Kamar"))
                item = self.tableWidgetTabel.horizontalHeaderItem(6)
                item.setText(_translate("MainWindow", "harga"))
                item = self.tableWidgetTabel.horizontalHeaderItem(7)
                item.setText(_translate("MainWindow", "tipe pembayaran"))
                item = self.tableWidgetTabel.horizontalHeaderItem(8)
                item.setText(_translate("MainWindow", "bulan ke"))
                item = self.tableWidgetTabel.horizontalHeaderItem(9)
                item.setText(_translate("MainWindow", "metode bayar"))
                item = self.tableWidgetTabel.horizontalHeaderItem(10)
                item.setText(_translate("MainWindow", "status"))
                item = self.tableWidgetTabel.horizontalHeaderItem(11)
                item.setText(_translate("MainWindow", "tanggal booking"))
                self.pushButtonKembali.setText(_translate("MainWindow", "Kembali"))
                self.pushButtonCari.setText(_translate("MainWindow", "Cari"))
                self.pushButtonHapus.setText(_translate("MainWindow", "Hapus"))

        def load_data(self):
                try:
                        conn = connection.get_connection()
                        cursor = conn.cursor()

                        query = """
                        SELECT 
                                p.id AS id_penghuni,
                                p.username,
                                p.nama_lengkap,
                                p.no_telp,
                                k.nomor_kamar,
                                t.nama_tipe,
                                t.harga,
                                pay.tipe_pembayaran,
                                pay.bulan_ke,
                                pay.metode_pembayaran,
                                pay.status,
                                b.tanggal_booking
                        FROM penghuni p
                        LEFT JOIN booking b ON p.id = b.id_penghuni
                        LEFT JOIN kamar k ON b.id_kamar = k.id_kamar
                        LEFT JOIN tipe_kamar t ON k.id_tipe = t.id_tipe
                        LEFT JOIN pembayaran pay ON b.id = pay.id_booking
                        ORDER BY p.id;
                        """

                        cursor.execute(query)
                        result = cursor.fetchall()

                        self.tableWidgetTabel.setRowCount(0)

                        for row_number, row_data in enumerate(result):
                                self.tableWidgetTabel.insertRow(row_number)
                        for column_number, data in enumerate(row_data):
                                self.tableWidgetTabel.setItem(
                                row_number,
                                column_number,
                                QtWidgets.QTableWidgetItem(str(data) if data is not None else "")
                                )

                        cursor.close()
                        conn.close()

                except Exception as e:
                        print("Error load data:", e)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
