# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detailkamarbiasa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import detailkamarbiasa_rc
from PyQt5.QtWidgets import QMessageBox
from pembayarankosbiasa import Ui_MainWindow as ui_bukapembayarankosbiasa
import user
from login import Ui_MainWindow as LoginUI   # Untuk membuka login kalau belum login



class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                self.MainWindow = MainWindow     # simpan referensi window

                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(424, 1014)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label_biasa = QtWidgets.QLabel(self.centralwidget)
                self.label_biasa.setGeometry(QtCore.QRect(30, 80, 371, 311))
                self.label_biasa.setStyleSheet("border-image: url(:/detailbiasa/Foto/biasa.jpeg);\n"
        "background-size: cover;")
                self.label_biasa.setText("")
                self.label_biasa.setObjectName("label_biasa")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(30, 20, 361, 51))
                self.label.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt; \n"
        " font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label.setObjectName("label")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.clicked.connect(self.kembali_ke_carikamar)


                self.pushButton.setGeometry(QtCore.QRect(40, 30, 101, 31))
                self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219),\n"
        "        stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 255);\n"
        "    border-radius: 8px;\n"
        "    border: none;\n"
        "    padding: 10px 25px;\n"
        "    font-size: 9px;\n"
        "    font-weight: bold;\n"
        "}")
                self.pushButton.setObjectName("pushButton")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(40, 90, 91, 31))
                self.label_2.setStyleSheet("background-color: qlineargradient(\n"
        "        spread:pad,\n"
        "        x1:0, y1:0,\n"
        "        x2:0, y2:0.715909,\n"
        "        stop:0 rgba(240, 235, 220, 255),  \n"
        "        stop:0.375 rgba(220, 215, 200, 255), \n"
        "        stop:0.835227 rgba(200, 190, 180, 255)\n"
        "    );\n"
        "    color: #4A4A4A;\n"
        "    font-weight: bold;\n"
        "    border-radius: 8px;\n"
        "    padding: 10px 15px;")
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(290, 100, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_3.setFont(font)
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(30, 370, 371, 581))
                self.label_4.setStyleSheet("background-color: #ffffff; color: #4A4A4A; font-size: 8pt; border-radius: 10px; border: 1px solid #E0E0E0; padding: 6px;")
                self.label_4.setText("")
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(40, 380, 211, 51))
                font = QtGui.QFont()
                font.setFamily("Verdana")
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.label_5.setFont(font)
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(220, 390, 161, 101))
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.label_6.setFont(font)
                self.label_6.setStyleSheet("background-color: qlineargradient("
                                        "spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,"
                                        "stop:0 rgba(255, 210, 80, 255),"
                                        "stop:1 rgba(255, 170, 30, 255));"
                                        "color: white; border-radius: 15px; padding: 10px;")
                self.label_6.setObjectName("label_6")
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(290, 410, 81, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_7.setFont(font)
                self.label_7.setStyleSheet("color:white;")
                self.label_7.setObjectName("label_7")
                self.label_8 = QtWidgets.QLabel(self.centralwidget)
                self.label_8.setGeometry(QtCore.QRect(310, 460, 54, 14))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_8.setFont(font)
                self.label_8.setStyleSheet("color:white;")
                self.label_8.setObjectName("label_8")
                self.label_9 = QtWidgets.QLabel(self.centralwidget)
                self.label_9.setGeometry(QtCore.QRect(40, 430, 161, 41))
                self.label_9.setObjectName("label_9")
                self.label_10 = QtWidgets.QLabel(self.centralwidget)
                self.label_10.setGeometry(QtCore.QRect(40, 510, 351, 41))
                font = QtGui.QFont()
                font.setPointSize(8)
                font.setBold(True)
                font.setWeight(75)
                self.label_10.setFont(font)
                self.label_10.setStyleSheet("background-color: qlineargradient("
                                        "spread:pad, x1:0, y1:0, x2:0, y2:0.715909,"
                                        "stop:0 rgba(240, 240, 240, 200),"
                                        "stop:0.375 rgba(220, 220, 220, 200),"
                                        "stop:0.835227 rgba(200, 200, 200, 200));"
                                        "color:#4A4A4A; border-radius:10px;")
                self.label_10.setObjectName("label_10")
                self.label_11 = QtWidgets.QLabel(self.centralwidget)
                self.label_11.setGeometry(QtCore.QRect(50, 570, 171, 31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setWeight(75)
                self.label_11.setFont(font)
                self.label_11.setObjectName("label_11")
                self.label_12 = QtWidgets.QLabel(self.centralwidget)
                self.label_12.setGeometry(QtCore.QRect(50, 650, 181, 31))
                self.label_12.setStyleSheet("background-color:white; color:#4A4A4A; border-radius:10px; border:1px solid #E0E0E0; padding:6px;")
                self.label_12.setObjectName("label_12")
                self.label_13 = QtWidgets.QLabel(self.centralwidget)
                self.label_13.setGeometry(QtCore.QRect(50, 690, 181, 31))
                self.label_13.setStyleSheet("background-color:white; color:#4A4A4A; border-radius:10px; border:1px solid #E0E0E0; padding:6px;")
                self.label_13.setObjectName("label_13")
                self.label_15 = QtWidgets.QLabel(self.centralwidget)
                self.label_15.setGeometry(QtCore.QRect(50, 610, 181, 31))
                self.label_15.setStyleSheet("background-color:white; color:#4A4A4A; border-radius:10px; border:1px solid #E0E0E0; padding:6px;")
                self.label_15.setObjectName("label_15")
                self.label_16 = QtWidgets.QLabel(self.centralwidget)
                self.label_16.setGeometry(QtCore.QRect(240, 610, 151, 31))
                self.label_16.setStyleSheet("background-color:white; color:#4A4A4A; border-radius:10px; border:1px solid #E0E0E0; padding:6px;")
                self.label_16.setObjectName("label_16")
                self.label_17 = QtWidgets.QLabel(self.centralwidget)
                self.label_17.setGeometry(QtCore.QRect(240, 650, 151, 31))
                self.label_17.setStyleSheet("background-color:white; color:#4A4A4A; border-radius:10px; border:1px solid #E0E0E0; padding:6px;")
                self.label_17.setObjectName("label_17")
                self.label_18 = QtWidgets.QLabel(self.centralwidget)
                self.label_18.setGeometry(QtCore.QRect(50, 750, 181, 16))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setWeight(75)
                self.label_18.setFont(font)
                self.label_18.setObjectName("label_18")
                self.label_19 = QtWidgets.QLabel(self.centralwidget)
                self.label_19.setGeometry(QtCore.QRect(50, 780, 331, 91))
                self.label_19.setStyleSheet("background-color:qlineargradient("
                                        "spread:pad, x1:0, y1:0, x2:0, y2:0.715909,"
                                        "stop:0 rgba(240,240,240,200),"
                                        "stop:0.375 rgba(220,220,220,200),"
                                        "stop:0.835227 rgba(200,200,200,200));"
                                        "border-radius:10px;")
                self.label_19.setText("")
                self.label_19.setObjectName("label_19")
                self.label_20 = QtWidgets.QLabel(self.centralwidget)
                self.label_20.setGeometry(QtCore.QRect(60, 790, 151, 31))
                self.label_20.setStyleSheet("background-color:white; color:#4A4A4A; border-radius:10px; padding:6px; border:1px solid #E0E0E0;")
                self.label_20.setObjectName("label_20")
                self.label_21 = QtWidgets.QLabel(self.centralwidget)
                self.label_21.setGeometry(QtCore.QRect(60, 830, 151, 31))
                self.label_21.setStyleSheet("background-color:white; color:#4A4A4A; border-radius:10px; padding:6px; border:1px solid #E0E0E0;")
                self.label_21.setObjectName("label_21")
                self.label_22 = QtWidgets.QLabel(self.centralwidget)
                self.label_22.setGeometry(QtCore.QRect(230, 790, 131, 31))
                self.label_22.setStyleSheet("background-color:white; color:#4A4A4A; border-radius:10px; padding:6px; border:1px solid #E0E0E0;")
                self.label_22.setObjectName("label_22")
                self.label_23 = QtWidgets.QLabel(self.centralwidget)
                self.label_23.setGeometry(QtCore.QRect(230, 830, 131, 31))
                self.label_23.setStyleSheet("background-color:white; color:#4A4A4A; border-radius:10px; padding:6px; border:1px solid #E0E0E0;")
                self.label_23.setObjectName("label_23")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.clicked.connect(self.ui_bukapembayaranbiasa)

                self.pushButton_2.setGeometry(QtCore.QRect(60, 890, 321, 41))
                self.pushButton_2.setStyleSheet("QPushButton#pushButton_2 {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,\n"
        "        stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color:white; border-radius:8px; padding:10px; font-size:14px; font-weight:bold;\n"
        "}")
                self.pushButton_2.setObjectName("pushButton_2")
                self.label_biasa.raise_()
                self.label_4.raise_()
                self.label_19.raise_()
                self.label.raise_()
                self.pushButton.raise_()
                self.label_2.raise_()
                self.label_3.raise_()
                self.label_5.raise_()
                self.label_6.raise_()
                self.label_7.raise_()
                self.label_8.raise_()
                self.label_9.raise_()
                self.label_10.raise_()
                self.label_11.raise_()
                self.label_12.raise_()
                self.label_13.raise_()
                self.label_15.raise_()
                self.label_16.raise_()
                self.label_17.raise_()
                self.label_18.raise_()
                self.label_20.raise_()
                self.label_21.raise_()
                self.label_22.raise_()
                self.label_23.raise_()
                self.pushButton_2.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 23))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                # ---------------------------
                # === CONNECT TOMBOL DI SINI ===
                # ---------------------------
                self.pushButton.clicked.connect(self.kembali_ke_carikamar)
                

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label.setText(_translate("MainWindow", "                           Detail Kamar KOS BIASA"))
                self.pushButton.setText(_translate("MainWindow", "<- Kembali"))
                self.label_2.setText(_translate("MainWindow", "Tersedia"))
                self.label_3.setText(_translate("MainWindow", "⭐️⭐️⭐️⭐️⭐️"))
                self.label_5.setText(_translate("MainWindow", "KOS BIASA "))
                self.label_6.setText(_translate("MainWindow", "Rp450.000 "))
                self.label_7.setText(_translate("MainWindow", "Harga Sewa"))
                self.label_8.setText(_translate("MainWindow", "/ bulan"))
                self.label_9.setText(_translate("MainWindow", "Kamar Nyaman & Ekonomis \nFasilitas Standar"))
                self.label_10.setText(_translate("MainWindow", "👤 1 Guest                 🛏️ 1 Bed              📐3x4 m "))
                self.label_11.setText(_translate("MainWindow", "🏠 Fasilitas Kamar"))
                self.label_12.setText(_translate("MainWindow", "✅Kamar Mandi Luar"))
                self.label_13.setText(_translate("MainWindow", "✅ free Kipas Angin"))
                self.label_15.setText(_translate("MainWindow", "✅ Kasur Busa Empuk"))
                self.label_16.setText(_translate("MainWindow", "✅Meja Kecil"))
                self.label_17.setText(_translate("MainWindow", "✅Lemari Pakaian"))
                self.label_18.setText(_translate("MainWindow", "🌟 Fasilitas Umum"))
                self.label_20.setText(_translate("MainWindow", "🅿️ Parkir Motor"))
                self.label_21.setText(_translate("MainWindow", "🧺Ruang Jemur"))
                self.label_22.setText(_translate("MainWindow", "🍳 Dapur Bersih"))
                self.label_23.setText(_translate("MainWindow", "🪴Taman Kecil"))
                self.pushButton_2.setText(_translate("MainWindow", "Pesan Sekarang"))

    

        def ui_bukapembayaranbiasa(self):

                if not user.is_logged_in:
                        QMessageBox.warning(None, "Login Dulu", "Anda harus login untuk memesan kamar!")

                        # buka login
                        self.MainWindow.close()
                        self.window = QtWidgets.QMainWindow()
                        self.login = LoginUI()
                        self.login.setupUi(self.window)
                        self.window.show()
                        return

                # Kalau SUDAH LOGIN → langsung buka pembayaran
                self.MainWindow.close()
                self.window = QtWidgets.QMainWindow()
                self.ui = ui_bukapembayarankosbiasa()
                self.ui.setupUi(self.window, prev_window=self) 
                self.ui.setupUi(self.window)
                self.window.show()

        

        
        def kembali_ke_carikamar(self):
                # Import di dalam fungsi agar tidak circular import
                from carikamar import Ui_MainWindow as Ui_CariKamar

                # Tutup window saat ini
                self.MainWindow.close()

                # Buka window Cari Kamar
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_CariKamar()
                self.ui.setupUi(self.window)
                self.window.show()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
