# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detailkamarvvip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import detailkamarvvip_rc
#from pembayarankosvvip import Ui_MainWindow as ui_bukapembayarankosvvip
import user
from login import Ui_MainWindow as LoginUI   # Untuk membuka login kalau belum login



class Ui_MainWindow(object):
        def setupUi(self, MainWindow, id_penghuni=None):
                self.id_penghuni = id_penghuni
                self.MainWindow = MainWindow 
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(387, 1015)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label_19 = QtWidgets.QLabel(self.centralwidget)
                self.label_19.setGeometry(QtCore.QRect(30, 810, 331, 91))
                self.label_19.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "background-color: qlineargradient(\n"
        "        spread:pad, \n"
        "        x1:0, y1:0, \n"
        "        x2:0, y2:0.715909, \n"
        "        /* Mulai dengan Abu-abu Sangat Terang (hampir putih) */\n"
        "        stop:0 rgba(240, 240, 240, 200),  \n"
        "        /* Tengah: Abu-abu Terang */\n"
        "        stop:0.375 rgba(220, 220, 220, 200), \n"
        "        /* Akhir: Abu-abu Agak Sedang */\n"
        "        stop:0.835227 rgba(200, 200, 200, 200) \n"
        "    );")
                self.label_19.setText("")
                self.label_19.setObjectName("label_19")
                self.label_11 = QtWidgets.QLabel(self.centralwidget)
                self.label_11.setGeometry(QtCore.QRect(30, 570, 171, 31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setWeight(75)
                self.label_11.setFont(font)
                self.label_11.setObjectName("label_11")
                self.label_16 = QtWidgets.QLabel(self.centralwidget)
                self.label_16.setGeometry(QtCore.QRect(220, 610, 151, 31))
                self.label_16.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_16.setObjectName("label_16")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(10, 20, 361, 51))
                self.label.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt; \n"
        " font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label.setObjectName("label")
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(270, 410, 81, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_7.setFont(font)
                self.label_7.setStyleSheet("color:rgba(255,255,255,210);")
                self.label_7.setObjectName("label_7")
                self.label_biasa = QtWidgets.QLabel(self.centralwidget)
                self.label_biasa.setGeometry(QtCore.QRect(10, 80, 371, 301))
                self.label_biasa.setStyleSheet("border-image: url(:/detailkamarvvip/Foto/vvip.jpeg);\n"
        "background-size: cover;")
                self.label_biasa.setText("")
                self.label_biasa.setObjectName("label_biasa")
                self.label_13 = QtWidgets.QLabel(self.centralwidget)
                self.label_13.setGeometry(QtCore.QRect(30, 690, 181, 31))
                self.label_13.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_13.setObjectName("label_13")
                self.label_23 = QtWidgets.QLabel(self.centralwidget)
                self.label_23.setGeometry(QtCore.QRect(210, 860, 131, 31))
                self.label_23.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt; \n"
        " font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_23.setObjectName("label_23")
                self.label_12 = QtWidgets.QLabel(self.centralwidget)
                self.label_12.setGeometry(QtCore.QRect(30, 650, 181, 31))
                self.label_12.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_12.setObjectName("label_12")
                self.label_22 = QtWidgets.QLabel(self.centralwidget)
                self.label_22.setGeometry(QtCore.QRect(210, 820, 131, 31))
                self.label_22.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt; \n"
        " font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_22.setObjectName("label_22")
                self.label_10 = QtWidgets.QLabel(self.centralwidget)
                self.label_10.setGeometry(QtCore.QRect(20, 510, 351, 41))
                font = QtGui.QFont()
                font.setPointSize(8)
                font.setBold(True)
                font.setWeight(75)
                self.label_10.setFont(font)
                self.label_10.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "background-color: qlineargradient(\n"
        "        spread:pad, \n"
        "        x1:0, y1:0, \n"
        "        x2:0, y2:0.715909, \n"
        "        /* Mulai dengan Abu-abu Sangat Terang (hampir putih) */\n"
        "        stop:0 rgba(240, 240, 240, 200),  \n"
        "        /* Tengah: Abu-abu Terang */\n"
        "        stop:0.375 rgba(220, 220, 220, 200), \n"
        "        /* Akhir: Abu-abu Agak Sedang */\n"
        "        stop:0.835227 rgba(200, 200, 200, 200) \n"
        "    );")
                self.label_10.setObjectName("label_10")
                self.label_9 = QtWidgets.QLabel(self.centralwidget)
                self.label_9.setGeometry(QtCore.QRect(20, 430, 161, 41))
                self.label_9.setObjectName("label_9")
                self.label_18 = QtWidgets.QLabel(self.centralwidget)
                self.label_18.setGeometry(QtCore.QRect(30, 780, 181, 16))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setWeight(75)
                self.label_18.setFont(font)
                self.label_18.setObjectName("label_18")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.clicked.connect(self.ui_bukapembayaranvvip)
                self.pushButton_2.setGeometry(QtCore.QRect(40, 910, 321, 41))
                self.pushButton_2.setStyleSheet("QPushButton#pushButton_2 {\n"
        "    /* Background Gradient Default */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219), /* Biru Tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)); /* Abu-abu Kebiruan */\n"
        "        \n"
        "    color: rgba(255, 255, 255, 255); /* Teks Putih Solid (lebih jelas) */\n"
        "    border-radius: 8px; /* Menggunakan 8px agar konsisten dengan elemen lain */\n"
        "    border: none; /* Pastikan tidak ada border bawaan */\n"
        "    padding: 10px 25px; /* Padding untuk tombol agar terlihat tebal */\n"
        "    font-size: 14px; /* Ukuran font yang konsisten */\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton#pushButton_2:hover {\n"
        "    /* Gradient Hover: Warna sedikit lebih cerah/kontras */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(40, 67, 98, 219), /* Biru Tua Sedikit Cerah */\n"
        "        stop:1 rgba(105, 118, 132, 226)); /* Abu-abu Kebiruan Sedikit Cerah */\n"
        "}\n"
        "\n"
        "QPushButton#pushButton_2:pressed {\n"
        "    /* Efek Pressed (Tombol Tertekan) */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    /* Memberikan ilusi tombol bergerak ke dalam */\n"
        "    background-color: rgba(105, 118, 132, 255); /* Warna solid yang lebih gelap/tertarik */\n"
        "    border-style: inset; /* Opsi lain: inset border */\n"
        "}")
                self.pushButton_2.setObjectName("pushButton_2")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(10, 370, 371, 601))
                self.label_4.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt; \n"
        " font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_4.setText("")
                self.label_4.setObjectName("label_4")
                self.label_21 = QtWidgets.QLabel(self.centralwidget)
                self.label_21.setGeometry(QtCore.QRect(40, 860, 151, 31))
                self.label_21.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt; \n"
        " font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_21.setObjectName("label_21")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(20, 90, 91, 31))
                self.label_2.setStyleSheet("background-color: qlineargradient(\n"
        "        spread:pad,\n"
        "        x1:0, y1:0,\n"
        "        x2:0, y2:0.715909,\n"
        "        /* Mulai: Krem Sangat Terang */\n"
        "        stop:0 rgba(240, 235, 220, 255),  \n"
        "        /* Tengah: Krem Muda */\n"
        "        stop:0.375 rgba(220, 215, 200, 255), \n"
        "        /* Akhir: Krem Agak Cokelat */\n"
        "        stop:0.835227 rgba(200, 190, 180, 255) \n"
        "    );\n"
        "\n"
        "    /* Ubah Teks menjadi Gelap (Abu-abu/Cokelat Gelap) agar Kontras di atas latar Krem */\n"
        "    color: #4A4A4A; \n"
        "    \n"
        "    font-weight: bold;\n"
        "    border-radius: 8px; \n"
        "    padding: 10px 15px;\n"
        "\n"
        "")
                self.label_2.setObjectName("label_2")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.clicked.connect(self.kembali_ke_carikamar)
                self.pushButton.setGeometry(QtCore.QRect(20, 30, 101, 31))
                self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
        "    /* Background Gradient Default */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219), /* Biru Tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)); /* Abu-abu Kebiruan */\n"
        "        \n"
        "    color: rgba(255, 255, 255, 255); /* Teks Putih Solid (lebih jelas) */\n"
        "    border-radius: 8px; /* Menggunakan 8px agar konsisten dengan elemen lain */\n"
        "    border: none; /* Pastikan tidak ada border bawaan */\n"
        "    padding: 10px 25px; /* Padding untuk tombol agar terlihat tebal */\n"
        "    font-size: 9px; /* Ukuran font yang konsisten */\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton#pushButton:hover {\n"
        "    /* Gradient Hover: Warna sedikit lebih cerah/kontras */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(40, 67, 98, 219), /* Biru Tua Sedikit Cerah */\n"
        "        stop:1 rgba(105, 118, 132, 226)); /* Abu-abu Kebiruan Sedikit Cerah */\n"
        "}\n"
        "\n"
        "QPushButton#pushButton:pressed {\n"
        "    /* Efek Pressed (Tombol Tertekan) */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    /* Memberikan ilusi tombol bergerak ke dalam */\n"
        "    background-color: rgba(105, 118, 132, 255); /* Warna solid yang lebih gelap/tertarik */\n"
        "    border-style: inset; /* Opsi lain: inset border */\n"
        "}")
                self.pushButton.setObjectName("pushButton")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(190, 380, 181, 101))
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.label_6.setFont(font)
                self.label_6.setStyleSheet("background-color: qlineargradient(\n"
        "    spread:pad,\n"
        "    x1:0, y1:0.5,\n"
        "    x2:1, y2:0.5,\n"
        "    stop:0 rgba(220, 60, 80, 255),     /* Ruby Red */\n"
        "    stop:1 rgba(150, 20, 40, 255)      /* Deep Ruby */\n"
        ");\n"
        "\n"
        "color: white;\n"
        "font-weight: bold;\n"
        "border-radius: 15px;\n"
        "padding: 10px 15px;\n"
        "border: none;\n"
        "")
                self.label_6.setObjectName("label_6")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(20, 380, 211, 51))
                font = QtGui.QFont()
                font.setFamily("Verdana")
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.label_5.setFont(font)
                self.label_5.setObjectName("label_5")
                self.label_14 = QtWidgets.QLabel(self.centralwidget)
                self.label_14.setGeometry(QtCore.QRect(220, 690, 151, 31))
                self.label_14.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_14.setObjectName("label_14")
                self.label_15 = QtWidgets.QLabel(self.centralwidget)
                self.label_15.setGeometry(QtCore.QRect(30, 610, 181, 31))
                self.label_15.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_15.setObjectName("label_15")
                self.label_20 = QtWidgets.QLabel(self.centralwidget)
                self.label_20.setGeometry(QtCore.QRect(40, 820, 151, 31))
                self.label_20.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 8pt; \n"
        " font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_20.setObjectName("label_20")
                self.label_8 = QtWidgets.QLabel(self.centralwidget)
                self.label_8.setGeometry(QtCore.QRect(300, 450, 54, 14))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_8.setFont(font)
                self.label_8.setStyleSheet("color:rgba(255,255,255,210);")
                self.label_8.setObjectName("label_8")
                self.label_17 = QtWidgets.QLabel(self.centralwidget)
                self.label_17.setGeometry(QtCore.QRect(220, 650, 151, 31))
                self.label_17.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_17.setObjectName("label_17")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(280, 140, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_3.setFont(font)
                self.label_3.setObjectName("label_3")
                self.label_24 = QtWidgets.QLabel(self.centralwidget)
                self.label_24.setGeometry(QtCore.QRect(270, 90, 101, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_24.setFont(font)
                self.label_24.setStyleSheet("background-color: qlineargradient(\n"
        "    spread:pad,\n"
        "    x1:0, y1:0.505682,\n"
        "    x2:1, y2:0.477,\n"
        "    stop:0 rgba(255, 210, 80, 255),   /* Kuning Gold Terang */\n"
        "    stop:1 rgba(255, 170, 30, 255)    /* Kuning Orange Emas */\n"
        ");\n"
        "\n"
        "color: rgba(255, 255, 255, 255);  /* Teks putih */\n"
        "font-weight: bold;\n"
        "border-radius: 15px;\n"
        "padding: 10px 15px;\n"
        "border: none;\n"
        "")
                self.label_24.setObjectName("label_24")
                self.label_25 = QtWidgets.QLabel(self.centralwidget)
                self.label_25.setGeometry(QtCore.QRect(280, 400, 81, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_25.setFont(font)
                self.label_25.setStyleSheet("color:rgba(255,255,255,210);")
                self.label_25.setObjectName("label_25")
                self.label_26 = QtWidgets.QLabel(self.centralwidget)
                self.label_26.setGeometry(QtCore.QRect(30, 730, 181, 31))
                self.label_26.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_26.setObjectName("label_26")
                self.label_27 = QtWidgets.QLabel(self.centralwidget)
                self.label_27.setGeometry(QtCore.QRect(220, 730, 151, 31))
                self.label_27.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_27.setObjectName("label_27")
                self.label_biasa.raise_()
                self.label_4.raise_()
                self.label_19.raise_()
                self.label_11.raise_()
                self.label_16.raise_()
                self.label.raise_()
                self.label_7.raise_()
                self.label_13.raise_()
                self.label_23.raise_()
                self.label_12.raise_()
                self.label_22.raise_()
                self.label_10.raise_()
                self.label_9.raise_()
                self.label_18.raise_()
                self.pushButton_2.raise_()
                self.label_21.raise_()
                self.label_2.raise_()
                self.pushButton.raise_()
                self.label_6.raise_()
                self.label_5.raise_()
                self.label_14.raise_()
                self.label_15.raise_()
                self.label_20.raise_()
                self.label_8.raise_()
                self.label_17.raise_()
                self.label_3.raise_()
                self.label_24.raise_()
                self.label_25.raise_()
                self.label_26.raise_()
                self.label_27.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 387, 23))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_11.setText(_translate("MainWindow", "🏠 Fasilitas Kamar"))
                self.label_16.setText(_translate("MainWindow", "✅Meja & kursi"))
                self.label.setText(_translate("MainWindow", "                           Detail Kamar KOS VVIP"))
                self.label_7.setText(_translate("MainWindow", "Harga Sewa"))
                self.label_13.setText(_translate("MainWindow", "✅ AC (Air Conditioner)"))
                self.label_23.setText(_translate("MainWindow", "🪴Taman Kecil"))
                self.label_12.setText(_translate("MainWindow", "✅Kamar Mandi Dalam"))
                self.label_22.setText(_translate("MainWindow", "🍳 Dapur Bersih"))
                self.label_10.setText(_translate("MainWindow", "👤 1 Guest               🛏️ 1 King Bed            📐5x5 m "))
                self.label_9.setText(_translate("MainWindow", "Kamar Premium dengan \n"
        "Fasilitas sangat Lengkap \n"
        " dan nyaman"))
                self.label_18.setText(_translate("MainWindow", "🌟 Fasilitas Umum"))
                self.pushButton_2.setText(_translate("MainWindow", "Pesan Sekarang"))
                self.label_21.setText(_translate("MainWindow", "🧺Ruang Jemur"))
                self.label_2.setText(_translate("MainWindow", "Tersedia"))
                self.pushButton.setText(_translate("MainWindow", "<- Kembali"))
                self.label_6.setText(_translate("MainWindow", "Rp1.200.000 "))
                self.label_5.setText(_translate("MainWindow", "KOS VVIP"))
                self.label_14.setText(_translate("MainWindow", "✅Water Heater"))
                self.label_15.setText(_translate("MainWindow", "✅King Bed Premium"))
                self.label_20.setText(_translate("MainWindow", "🅿️ Parkir Motor"))
                self.label_8.setText(_translate("MainWindow", "/ bulan"))
                self.label_17.setText(_translate("MainWindow", "✅Lemari Pakaian"))
                self.label_3.setText(_translate("MainWindow", "⭐️⭐️⭐️⭐️⭐️"))
                self.label_24.setText(_translate("MainWindow", "👑 VVIP"))
                self.label_25.setText(_translate("MainWindow", "Harga Sewa"))
                self.label_26.setText(_translate("MainWindow", "✅Cermin Besar"))
                self.label_27.setText(_translate("MainWindow", "✅Cleaning Service"))
        

        def ui_bukapembayaranvvip(self):
                from pembayarankosvvip import Ui_MainWindow as ui_bukapembayarankosvvip

                if not user.is_logged_in:
                        QMessageBox.warning(None, "Login Dulu", "Anda harus login untuk memesan kamar!")

                        # buka login
                        self.MainWindow.close()
                        self.window = QtWidgets.QMainWindow()
                        self.login = LoginUI()
                        self.login.setupUi(self.window)
                        self.window.show()
                        return

                # Kalau sudah LOGIN → buka pembayaran
                self.MainWindow.close()
                self.window = QtWidgets.QMainWindow()
                self.ui = ui_bukapembayarankosvvip()

                # ⬇⬇⬇ WAJIB! KIRIM id_penghuni KE HALAMAN PEMBAYARAN
                self.ui.setupUi(self.window, self.id_penghuni)

                self.window.show()



        

        
        def kembali_ke_carikamar(self):
                from carikamar import Ui_MainWindow   # Import di dalam fungsi
                
                self.MainWindow.close()
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_MainWindow()
                self.ui.setupUi(self.window)
                self.window.show()
               

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
