# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from connection import get_connection
#from carikamar import Ui_MainWindow as CariKamarUI
from dashboardadmin import Ui_MainWindow as AdminDashboardUI
from dashboardpenghuni import Ui_MainWindow as PenghuniDashboardUI
import user
import login_rc
#from signup import Ui_MainWindow as bukasignup


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                self.MainWindow = MainWindow

                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(450, 550)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.widget = QtWidgets.QWidget(self.centralwidget)
                self.widget.setGeometry(QtCore.QRect(50, 20, 370, 480))
                self.widget.setObjectName("widget")
                self.label = QtWidgets.QLabel(self.widget)
                self.label.setGeometry(QtCore.QRect(10, 10, 351, 461))
                self.label.setStyleSheet("border-image: url(:/login/Foto/bg.jpg);\n"
        "border-radius:20px;")
                self.label.setText("")
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.widget)
                self.label_2.setGeometry(QtCore.QRect(10, 10, 351, 461))
                self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
        "border-radius:20px;")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.widget)
                self.label_3.setGeometry(QtCore.QRect(30, 30, 311, 411))
                self.label_3.setStyleSheet("background-color:rgba(0,0,0,100);\n"
        "border-radius:20px;")
                self.label_3.setText("")
                self.label_3.setObjectName("label_3")
                self.labelLogin = QtWidgets.QLabel(self.widget)
                self.labelLogin.setGeometry(QtCore.QRect(140, 79, 121, 41))
                font = QtGui.QFont()
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.labelLogin.setFont(font)
                self.labelLogin.setStyleSheet("color:rgba(255,255,255,210);")
                self.labelLogin.setObjectName("labelLogin")
                self.lineEditUsername = QtWidgets.QLineEdit(self.widget)
                self.lineEditUsername.setGeometry(QtCore.QRect(70, 150, 231, 41))
                self.lineEditUsername.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        "border: none;\n"
        "border-bottom: 2px solid #ffffff; \n"
        "color: rgba(255,255,255,0.9);\n"
        "padding-bottom: 7px;\n"
        "color: white;\n"
        "\n"
        "outline: none;\n"
        "width: 100%; ")
                self.lineEditUsername.setObjectName("lineEditUsername")
                self.lineEditPassword = QtWidgets.QLineEdit(self.widget)
                self.lineEditPassword.setGeometry(QtCore.QRect(70, 220, 231, 41))
                self.lineEditPassword.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        "border: none;\n"
        "border-bottom: 2px solid #ffffff; \n"
        "color: rgba(255,255,255,0.9);\n"
        "padding-bottom: 7px;\n"
        "\n"
        "\n"
        "outline: none;\n"
        "width: 100%; ")
                self.lineEditPassword.setObjectName("lineEditPassword")
                self.pushButtonLogIn = QtWidgets.QPushButton(self.widget)
                self.pushButtonLogIn.clicked.connect(self.login)
                self.pushButtonLogIn.setGeometry(QtCore.QRect(120, 320, 131, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.pushButtonLogIn.setFont(font)
                self.pushButtonLogIn.setStyleSheet("QPushButton#pushButtonLogIn{\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color:rgba(255, 255, 255, 210);\n"
        "    border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonLogIn:hover{\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonLogIn:pressed{\n"
        "    padding-left:5px;\n"
        "    padding-top:5px;\n"
        "    background-color:rgba(105,118,132,200);\n"
        "}")
                self.pushButtonLogIn.setObjectName("pushButtonLogIn")
                self.labelDont = QtWidgets.QLabel(self.widget)
                self.labelDont.setGeometry(QtCore.QRect(80, 360, 101, 16))
                font = QtGui.QFont()
                font.setPointSize(7)
                self.labelDont.setFont(font)
                self.labelDont.setStyleSheet("color:rgba(255,255,255,210);")
                self.labelDont.setObjectName("labelDont")
                self.pushButtonSignUp = QtWidgets.QPushButton(self.widget)
                self.pushButtonSignUp.clicked.connect(self.signup)
                self.pushButtonSignUp.setGeometry(QtCore.QRect(180, 360, 82, 25))
                self.pushButtonSignUp.setStyleSheet("QPushButton#pushButtonSignUp{\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color:rgba(255, 255, 255, 210);\n"
        "    border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonSignUp:hover{\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonSignUp:pressed{\n"
        "    padding-left:5px;\n"
        "    padding-top:5px;\n"
        "    background-color:rgba(105,118,132,200);\n"
        "}")
                self.pushButtonSignUp.setObjectName("pushButtonSignUp")
                self.pushButtonMasukSebagaiTamu = QtWidgets.QPushButton(self.widget)
                self.pushButtonMasukSebagaiTamu.clicked.connect(self.openGuestPage)

                self.pushButtonMasukSebagaiTamu.setGeometry(QtCore.QRect(100, 280, 181, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.pushButtonMasukSebagaiTamu.setFont(font)
                self.pushButtonMasukSebagaiTamu.setStyleSheet("QPushButton#pushButtonMasukSebagaiTamu{\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color:rgba(255, 255, 255, 210);\n"
        "    border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonMasukSebagaiTamu:hover{\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonMasukSebagaiTamu:pressed{\n"
        "    padding-left:5px;\n"
        "    padding-top:5px;\n"
        "    background-color:rgba(105,118,132,200);\n"
        "}")
                self.pushButtonMasukSebagaiTamu.setObjectName("pushButtonMasukSebagaiTamu")
                self.label_2.raise_()
                self.label.raise_()
                self.label_3.raise_()
                self.labelLogin.raise_()
                self.lineEditUsername.raise_()
                self.lineEditPassword.raise_()
                self.pushButtonLogIn.raise_()
                self.labelDont.raise_()
                self.pushButtonSignUp.raise_()
                self.pushButtonMasukSebagaiTamu.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 23))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.labelLogin.setText(_translate("MainWindow", "LOG IN"))
                self.lineEditUsername.setPlaceholderText(_translate("MainWindow", "Username"))
                self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Password"))
                self.pushButtonLogIn.setText(_translate("MainWindow", "LOG IN"))
                self.labelDont.setText(_translate("MainWindow", "Belum punya akun?"))
                self.pushButtonSignUp.setText(_translate("MainWindow", "Sign up "))
                self.pushButtonMasukSebagaiTamu.setText(_translate("MainWindow", "Masuk Sebagai Tamu"))

        def login(self):
                username = self.lineEditUsername.text()
                password = self.lineEditPassword.text()

                if username == "" or password == "":
                        QMessageBox.warning(None, "Error", "Username dan password wajib diisi!")
                        return

                try:
                        db = get_connection()
                        cursor = db.cursor(dictionary=True)  # penting, supaya hasil fetch berupa dict

                        # --- Cek admin ---
                        sql_admin = "SELECT * FROM admin WHERE username=%s AND password=%s"
                        cursor.execute(sql_admin, (username, password))
                        admin = cursor.fetchone()

                        if admin:
                                QMessageBox.information(None, "Sukses", "Login sebagai ADMIN berhasil!")
                                user.is_logged_in = True
                                user.current_user = admin  # simpan seluruh data admin
                                self.newWindow = QtWidgets.QMainWindow()
                                self.admin_ui = AdminDashboardUI()
                                self.admin_ui.setupUi(self.newWindow)
                                self.newWindow.show()
                                self.MainWindow.close()
                                return

                        # --- Cek penghuni ---
                        sql_penghuni = "SELECT * FROM penghuni WHERE username=%s AND password=%s"
                        cursor.execute(sql_penghuni, (username, password))
                        penghuni = cursor.fetchone()

                        if penghuni:
                                QMessageBox.information(None, "Sukses", "Login sebagai PENGHUNI berhasil!")
                                user.is_logged_in = True
                                user.current_user = penghuni  # simpan seluruh data penghuni
                                self.newWindow = QtWidgets.QMainWindow()
                                self.penghuni_ui = PenghuniDashboardUI()
                                self.penghuni_ui.setupUi(self.newWindow)
                                self.newWindow.show()
                                self.MainWindow.close()
                                return

                        # Kalau keduanya tidak ada
                        QMessageBox.warning(None, "Gagal", "Username atau password salah!")
                        self.lineEditUsername.clear()
                        self.lineEditPassword.clear()

                except Exception as e:
                        QMessageBox.critical(None, "Error", str(e))


        def openGuestPage(self):
                import carikamar
                self.newWindow = QtWidgets.QMainWindow()
                self.cari = carikamar.Ui_MainWindow()
                self.cari.setupUi(self.newWindow)
                self.newWindow.show()
                self.MainWindow.close()

                # <── menutup window login
        def signup(self):
                from signup import Ui_MainWindow as SignupWindow  
                
                self.signupWindow = QtWidgets.QMainWindow()
                self.signupUI = SignupWindow()
                self.signupUI.setupUi(self.signupWindow)
                self.signupWindow.show()
                self.MainWindow.close()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())