# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pembayarankosvip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tfbank import Ui_MainWindow as ui_bukatfbank
from ewalllet import Ui_EwalletWindow
from tunai import Ui_TunaiWindow
import pembayarankosvip_rc



class Ui_MainWindow(object):
        def setupUi(self, MainWindow, id_penghuni,id_booking):
                self.id_booking = id_booking
                self.id_penghuni = id_penghuni
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(383, 767)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(160, 200, 151, 41))
                self.label_6.setStyleSheet("color:rgba(255,255,255,210);")
                self.label_6.setObjectName("label_6")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(30, 130, 311, 141))
                self.label_3.setStyleSheet("background-color: qlineargradient(\n"
        "    spread:pad,\n"
        "    x1:0, y1:0.5,\n"
        "    x2:1, y2:0.5,\n"
        "    stop:0 rgba(180, 140, 255, 255),   /* Soft Purple */\n"
        "    stop:1 rgba(140, 90, 230, 255)     /* Deeper Soft Purple */\n"
        ");\n"
        "\n"
        "color: rgba(255, 255, 255, 255);\n"
        "font-weight: bold;\n"
        "border-radius: 15px;\n"
        "padding: 10px 15px;\n"
        "border: none;\n"
        "")
                self.label_3.setText("")
                self.label_3.setObjectName("label_3")
                self.label_10 = QtWidgets.QLabel(self.centralwidget)
                self.label_10.setGeometry(QtCore.QRect(210, 330, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_10.setFont(font)
                self.label_10.setObjectName("label_10")
                self.label_12 = QtWidgets.QLabel(self.centralwidget)
                self.label_12.setGeometry(QtCore.QRect(40, 380, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_12.setFont(font)
                self.label_12.setObjectName("label_12")
                self.label_8 = QtWidgets.QLabel(self.centralwidget)
                self.label_8.setGeometry(QtCore.QRect(40, 310, 281, 16))
                self.label_8.setObjectName("label_8")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(40, 140, 111, 121))
                self.label_4.setStyleSheet("border-image: url(:/pembayarankosvip/Foto/vip.jpeg);\n"
        "background-size: cover;")
                self.label_4.setText("")
                self.label_4.setObjectName("label_4")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(10, 20, 351, 701))
                self.label.setStyleSheet("color:rgba(255,255,255,210);\n"
        "background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt; \n"
        " font-weight: bold;               /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label.setText("")
                self.label.setObjectName("label")
                self.label_17 = QtWidgets.QLabel(self.centralwidget)
                self.label_17.setGeometry(QtCore.QRect(230, 470, 111, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_17.setFont(font)
                self.label_17.setStyleSheet("color:rgba(255,255,255,210);")
                self.label_17.setObjectName("label_17")
                self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
                self.radioButton_3.setGeometry(QtCore.QRect(40, 610, 291, 18))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_3.setFont(font)
                self.radioButton_3.setObjectName("radioButton_3")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(80, 80, 221, 31))
                font = QtGui.QFont()
                font.setPointSize(17)
                font.setBold(True)
                font.setWeight(75)
                self.label_2.setFont(font)
                self.label_2.setObjectName("label_2")
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(40, 280, 291, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_7.setFont(font)
                self.label_7.setObjectName("label_7")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(160, 170, 151, 21))
                font = QtGui.QFont()
                font.setPointSize(17)
                font.setBold(True)
                font.setWeight(75)
                self.label_5.setFont(font)
                self.label_5.setStyleSheet("color:rgba(255,255,255,210);")
                self.label_5.setObjectName("label_5")
                self.label_11 = QtWidgets.QLabel(self.centralwidget)
                self.label_11.setGeometry(QtCore.QRect(30, 370, 311, 81))
                self.label_11.setStyleSheet("background-color: #ffffff;      /* Putih seperti di gambar */\n"
        "    color: #4A4A4A;                 /* Teks abu tua */\n"
        "    font-size: 10pt;                /* Sesuaikan selera */\n"
        "    \n"
        "    border-radius: 10px;            /* Biar pill / rounded */\n"
        "    border: 1px solid #E0E0E0;      /* Garis tipis abu terang (optional) */\n"
        "\n"
        "    padding-left: 12px;             /* Padding dalam */\n"
        "    padding-right: 12px;\n"
        "    padding-top: 6px;\n"
        "    padding-bottom: 6px;")
                self.label_11.setText("")
                self.label_11.setObjectName("label_11")
                self.label_9 = QtWidgets.QLabel(self.centralwidget)
                self.label_9.setGeometry(QtCore.QRect(40, 330, 151, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_9.setFont(font)
                self.label_9.setObjectName("label_9")
                self.label_15 = QtWidgets.QLabel(self.centralwidget)
                self.label_15.setGeometry(QtCore.QRect(30, 460, 311, 41))
                self.label_15.setStyleSheet("background-color: qlineargradient(\n"
        "    spread:pad,\n"
        "    x1:0, y1:0.505682,\n"
        "    x2:1, y2:0.477,\n"
        "    stop:0 rgba(80, 220, 120, 255),    /* Hijau Terang Fresh */\n"
        "    stop:1 rgba(30, 160, 80, 255)      /* Hijau Lebih Gelap */\n"
        ");\n"
        "\n"
        "color: rgba(255, 255, 255, 255);  /* Teks putih */\n"
        "font-weight: bold;\n"
        "border-radius: 15px;\n"
        "padding: 10px 15px;\n"
        "border: none;\n"
        "")
                self.label_15.setText("")
                self.label_15.setObjectName("label_15")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(30, 40, 101, 31))
                self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
        "    /* Background Gradient Default */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(20, 47, 78, 219), /* Biru Tua */\n"
        "        stop:1 rgba(85, 98, 112, 226)); /* Abu-abu Kebiruan */\n"
        "        \n"
        "    color: rgba(255, 255, 255, 255); /* Teks Putih Solid (lebih jelas) */\n"
        "    border-radius: 8px; /* Menggunakan 8px agar konsisten dengan elemen lain */\n"
        "    border: none; /* Pastikan tidak ada border bawaan */\n"
        "    padding: 10px 25px; /* Padding untuk tombol agar terlihat tebal */\n"
        "    font-size: 9px; /* Ukuran font yang konsisten */\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton#pushButton:hover {\n"
        "    /* Gradient Hover: Warna sedikit lebih cerah/kontras */\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
        "        stop:0 rgba(40, 67, 98, 219), /* Biru Tua Sedikit Cerah */\n"
        "        stop:1 rgba(105, 118, 132, 226)); /* Abu-abu Kebiruan Sedikit Cerah */\n"
        "}\n"
        "\n"
        "QPushButton#pushButton:pressed {\n"
        "    /* Efek Pressed (Tombol Tertekan) */\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    /* Memberikan ilusi tombol bergerak ke dalam */\n"
        "    background-color: rgba(105, 118, 132, 255); /* Warna solid yang lebih gelap/tertarik */\n"
        "    border-style: inset; /* Opsi lain: inset border */\n"
        "}")
                self.pushButton.setObjectName("pushButton")
                self.label_18 = QtWidgets.QLabel(self.centralwidget)
                self.label_18.setGeometry(QtCore.QRect(40, 520, 171, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_18.setFont(font)
                self.label_18.setObjectName("label_18")
                self.label_16 = QtWidgets.QLabel(self.centralwidget)
                self.label_16.setGeometry(QtCore.QRect(40, 470, 111, 16))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_16.setFont(font)
                self.label_16.setObjectName("label_16")
                self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
                self.radioButton_2.setGeometry(QtCore.QRect(40, 580, 291, 18))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_2.setFont(font)
                self.radioButton_2.setObjectName("radioButton_2")
                self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
                self.radioButton.setGeometry(QtCore.QRect(40, 550, 281, 21))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.radioButton.setFont(font)
                self.radioButton.setObjectName("radioButton")
                self.label_14 = QtWidgets.QLabel(self.centralwidget)
                self.label_14.setGeometry(QtCore.QRect(230, 410, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_14.setFont(font)
                self.label_14.setObjectName("label_14")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.clicked.connect(self.buka_metode_pembayaran)

                self.pushButton_2.setGeometry(QtCore.QRect(40, 650, 301, 51))
                self.pushButton_2.setStyleSheet("background-color: qlineargradient(\n"
        "    spread:pad,\n"
        "    x1:0, y1:0.5,\n"
        "    x2:1, y2:0.5,\n"
        "    stop:0 rgba(180, 140, 255, 255),   /* Soft Purple */\n"
        "    stop:1 rgba(140, 90, 230, 255)     /* Deeper Soft Purple */\n"
        ");\n"
        "\n"
        "color: rgba(255, 255, 255, 255);\n"
        "font-weight: bold;\n"
        "border-radius: 15px;\n"
        "padding: 10px 15px;\n"
        "border: none;\n"
        "")
                self.pushButton_2.setObjectName("pushButton_2")
                self.label_13 = QtWidgets.QLabel(self.centralwidget)
                self.label_13.setGeometry(QtCore.QRect(160, 200, 151, 41))
                self.label_13.setStyleSheet("color:rgba(255,255,255,210);")
                self.label_13.setObjectName("label_13")
                self.label.raise_()
                self.label_6.raise_()
                self.label_3.raise_()
                self.label_10.raise_()
                self.label_8.raise_()
                self.label_4.raise_()
                self.radioButton_3.raise_()
                self.label_2.raise_()
                self.label_7.raise_()
                self.label_5.raise_()
                self.label_11.raise_()
                self.label_9.raise_()
                self.label_15.raise_()
                self.pushButton.raise_()
                self.label_18.raise_()
                self.label_16.raise_()
                self.radioButton_2.raise_()
                self.radioButton.raise_()
                self.label_14.raise_()
                self.pushButton_2.raise_()
                self.label_13.raise_()
                self.label_12.raise_()
                self.label_17.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 383, 23))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_6.setText(_translate("MainWindow", "1 Orang \n"
        "\n"
        " Kamar mandi luar"))
                self.label_10.setText(_translate("MainWindow", "1 Bulan"))
                self.label_12.setText(_translate("MainWindow", "Rincian Biaya"))
                self.label_8.setText(_translate("MainWindow", "Tanggal                                Durasi"))
                self.label_17.setText(_translate("MainWindow", "Rp 450.000"))
                self.radioButton_3.setText(_translate("MainWindow", "💵 Bayar Tunai"))
                self.label_2.setText(_translate("MainWindow", "Pembayaran Kos"))
                self.label_7.setText(_translate("MainWindow", "Periode Sewa"))
                self.label_5.setText(_translate("MainWindow", "KOS VIP"))
                self.label_9.setText(_translate("MainWindow", "Auto"))
                self.pushButton.setText(_translate("MainWindow", "<- Kembali"))
                self.label_18.setText(_translate("MainWindow", "Metode Pembayaran"))
                self.label_16.setText(_translate("MainWindow", "Total Pembayaran"))
                self.radioButton_2.setText(_translate("MainWindow", " 💳 Transfer Bank"))
                self.radioButton.setText(_translate("MainWindow", "📱 E- WALLET"))
                self.label_14.setText(_translate("MainWindow", "Rp750.000 "))
                self.pushButton_2.setText(_translate("MainWindow", "Bayar Sekarang"))
                self.label_13.setText(_translate("MainWindow", "1 Orang \n"
        "\n"
        " Kamar mandi Dalam"))
        def buka_metode_pembayaran(self):
                if self.radioButton.isChecked():
                # E-WALLET
                        self.window = QtWidgets.QMainWindow()
                        self.ui = Ui_EwalletWindow()
                        self.ui.setupUi(self.window)
                        self.window.show()

                elif self.radioButton_2.isChecked():
                # TRANSFER BANK
                        self.window = QtWidgets.QMainWindow()
                        self.ui = ui_bukatfbank()
                        self.ui.setupUi(self.window)
                        self.window.show()

                elif self.radioButton_3.isChecked():
                # BAYAR TUNAI
                        self.window = QtWidgets.QMainWindow()
                        self.ui = Ui_TunaiWindow()
                        self.ui.setupUi(self.window)
                        self.window.show()

                else:
                        pesan = QtWidgets.QMessageBox()
                        pesan.setWindowTitle("Peringatan")
                        pesan.setText("Silakan pilih metode pembayaran!")
                        pesan.setIcon(QtWidgets.QMessageBox.Warning)
                        pesan.exec_()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

