# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import signup_rc
from PyQt5.QtWidgets import QMessageBox
import connection
#from login import Ui_MainWindow as LoginWindow




class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                self.MainWindow = MainWindow

                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(450, 584)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(50, 30, 351, 521))
                self.label.setStyleSheet("border-image: url(:/singup/Foto/bg.jpg);\n"
        "border-radius : 20px;")
                self.label.setText("")
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(72, 50, 311, 481))
                self.label_2.setStyleSheet("border-image: url(:/newPrefix/foto2.jpg);\n"
        "border-radius:20px;")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.labelSignUp = QtWidgets.QLabel(self.centralwidget)
                self.labelSignUp.setGeometry(QtCore.QRect(170, 60, 121, 41))
                font = QtGui.QFont()
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.labelSignUp.setFont(font)
                self.labelSignUp.setStyleSheet("color:rgba(255,255,255,210);")
                self.labelSignUp.setObjectName("labelSignUp")
                self.lineEditNamaLengkap = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEditNamaLengkap.setGeometry(QtCore.QRect(110, 130, 231, 31))
                self.lineEditNamaLengkap.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        "border: none;\n"
        "border-bottom: 2px solid #ffffff; \n"
        "color: rgba(255,255,255,0.9);\n"
        "padding-bottom: 7px;\n"
        "color: white;\n"
        "\n"
        "outline: none;\n"
        "width: 100%; ")
                self.lineEditNamaLengkap.setObjectName("lineEditNamaLengkap")
                self.lineEditUsername = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEditUsername.setGeometry(QtCore.QRect(110, 180, 231, 31))
                self.lineEditUsername.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        "border: none;\n"
        "border-bottom: 2px solid #ffffff; \n"
        "color: rgba(255,255,255,0.9);\n"
        "padding-bottom: 7px;\n"
        "color: white;\n"
        "\n"
        "outline: none;\n"
        "width: 100%; ")
                self.lineEditUsername.setObjectName("lineEditUsername")
                self.lineEditEmail = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEditEmail.setGeometry(QtCore.QRect(110, 230, 231, 31))
                self.lineEditEmail.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        "border: none;\n"
        "border-bottom: 2px solid #ffffff; \n"
        "color: rgba(255,255,255,0.9);\n"
        "padding-bottom: 7px;\n"
        "color: white;\n"
        "\n"
        "outline: none;\n"
        "width: 100%; ")
                self.lineEditEmail.setObjectName("lineEditEmail")
                self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEditPassword.setGeometry(QtCore.QRect(110, 280, 231, 31))
                self.lineEditPassword.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        "border: none;\n"
        "border-bottom: 2px solid #ffffff; \n"
        "color: rgba(255,255,255,0.9);\n"
        "padding-bottom: 7px;\n"
        "color: white;\n"
        "\n"
        "outline: none;\n"
        "width: 100%; ")
                self.lineEditPassword.setObjectName("lineEditPassword")
                self.pushButtonDaftar = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonDaftar.clicked.connect(self.insertData)

                self.pushButtonDaftar.setGeometry(QtCore.QRect(110, 440, 75, 23))
                self.pushButtonDaftar.setStyleSheet("/* Style untuk tombol daftar */\n"
        "QPushButton#pushButtonDaftar {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonDaftar:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonDaftar:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}\n"
        "")
                self.pushButtonDaftar.setObjectName("pushButtonDaftar")
                self.pushButtonBatal = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonBatal.clicked.connect(self.closeWindow)
                
                

                self.pushButtonBatal.setGeometry(QtCore.QRect(190, 440, 75, 23))
                self.pushButtonBatal.setStyleSheet("/* Style untuk tombol hapus */\n"
        "QPushButton#pushButtonBatal {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonBatal:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonBatal:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}\n"
        "")
                self.pushButtonBatal.setObjectName("pushButtonBatal")
                self.pushButtonReset = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonReset.clicked.connect(self.resetForm)
                self.pushButtonReset.setGeometry(QtCore.QRect(270, 440, 75, 23))
                self.pushButtonReset.setStyleSheet("/* Style untuk tombol hapus */\n"
        "QPushButton#pushButtonReset{\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonReset:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonReset:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}\n"
        "")
                self.pushButtonReset.setObjectName("pushButtonReset")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(120, 500, 111, 16))
                self.label_4.setStyleSheet("color : white;")
                self.label_4.setObjectName("label_4")
                self.pushButtonLogIn = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonLogIn.clicked.connect(self.openLoginPage)
                self.pushButtonLogIn.setGeometry(QtCore.QRect(240, 490, 75, 22))
                self.pushButtonLogIn.setStyleSheet("/* Style untuk tombol hapus */\n"
        "QPushButton#pushButtonLogIn{\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "    color: rgba(255, 255, 255, 210);\n"
        "    border-radius: 5px;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonLogIn:hover {\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
        "}\n"
        "\n"
        "QPushButton#pushButtonLogIn:pressed {\n"
        "    padding-left: 5px;\n"
        "    padding-top: 5px;\n"
        "    background-color: rgba(105, 118, 132, 200);\n"
        "}\n"
        "")
                self.pushButtonLogIn.setObjectName("pushButtonLogIn")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(50, 30, 351, 511))
                self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
        "border-radius:10px;")
                self.label_3.setText("")
                self.label_3.setObjectName("label_3")
                self.lineEdittlp = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdittlp.setGeometry(QtCore.QRect(110, 330, 231, 20))
                self.lineEdittlp.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        "border: none;\n"
        "border-bottom: 2px solid #ffffff; \n"
        "color: rgba(255,255,255,0.9);\n"
        "padding-bottom: 7px;\n"
        "color: white;\n"
        "\n"
        "outline: none;\n"
        "width: 100%; ")
                self.lineEdittlp.setObjectName("lineEdittlp")
                self.label.raise_()
                self.label_3.raise_()
                self.label_2.raise_()
                self.labelSignUp.raise_()
                self.lineEditNamaLengkap.raise_()
                self.lineEditUsername.raise_()
                self.lineEditEmail.raise_()
                self.lineEditPassword.raise_()
                self.pushButtonDaftar.raise_()
                self.pushButtonBatal.raise_()
                self.pushButtonReset.raise_()
                self.label_4.raise_()
                self.pushButtonLogIn.raise_()
                self.lineEdittlp.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 23))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.labelSignUp.setText(_translate("MainWindow", "Sign Up"))
                self.lineEditNamaLengkap.setPlaceholderText(_translate("MainWindow", "Nama Lengkap"))
                self.lineEditUsername.setPlaceholderText(_translate("MainWindow", "Username"))
                self.lineEditEmail.setPlaceholderText(_translate("MainWindow", "Email"))
                self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Password"))
                self.pushButtonDaftar.setText(_translate("MainWindow", "Daftar"))
                self.pushButtonBatal.setText(_translate("MainWindow", "Batal"))
                self.pushButtonReset.setText(_translate("MainWindow", "Reset"))
                self.label_4.setText(_translate("MainWindow", "Sudah Punya Akun?"))
                self.pushButtonLogIn.setText(_translate("MainWindow", "LogIn"))
                self.lineEdittlp.setPlaceholderText(_translate("MainWindow", "no.tlp"))

        def insertData(self):
                
               

                nama = self.lineEditNamaLengkap.text().strip()
                username = self.lineEditUsername.text().strip()
                email = self.lineEditEmail.text().strip()
                password = self.lineEditPassword.text().strip()
                telp = self.lineEdittlp.text().strip()

                # =====================
                # VALIDASI FIELD KOSONG
                # =====================
                if not nama or not username or not email or not password or not telp:
                        QMessageBox.warning(None, "Form Tidak Lengkap", "Semua field wajib diisi!")
                        return

                try:
                        conn = connection.get_connection()
                        cursor = conn.cursor()

                        sql = """
                        INSERT INTO penghuni (nama_lengkap, username, email, password, no_telp, created_at)
                        VALUES (%s, %s, %s, %s, %s, NOW())
                        """

                        cursor.execute(sql, (nama, username, email, password, telp))
                        conn.commit()

                        QMessageBox.information(None, "Berhasil", "Pendaftaran berhasil!")

                        # Bersihkan form
                        self.lineEditNamaLengkap.clear()
                        self.lineEditUsername.clear()
                        self.lineEditEmail.clear()
                        self.lineEditPassword.clear()
                        self.lineEdittlp.clear()

                except Exception as e:
                        QMessageBox.critical(None, "Error", f"Terjadi kesalahan:\n{e}")

        def closeWindow(self):
                self.MainWindow.close()

        def resetForm(self):
                self.lineEditNamaLengkap.clear()
                self.lineEditUsername.clear()
                self.lineEditEmail.clear()
                self.lineEditPassword.clear()
                self.lineEdittlp.clear()

        def openLoginPage(self):
                from login import Ui_MainWindow as LoginWindow

                self.loginWindow = QtWidgets.QMainWindow()
                self.loginUI = LoginWindow()
                self.loginUI.setupUi(self.loginWindow)
                self.loginWindow.show()
                self.MainWindow.close()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
